### ISSUE TITLE
请问有较成熟的prompt learning的训练和推理框架可用么

### ISSUE THREAD

**Issue by liuyixian0317** [IDEA-CCNL/Fengshenbang-LM#117]
您好，请问二郎神刷榜few shot和zero shot的任务是用的prompt learning的范式么，是否有开源的prompt learning框架呢。

**Comment by suolyer** [comment]
hi ~@liuyixian0317，针对 Few/Zero-Shot 场景，我们基于二郎神专门开发了一个新模型，近期内不久就会发布

**Comment by suolyer** [comment]
> 您好，请问prompt learning框架什么时候会发布呢。

hi~，我们最新被 EMNLP2022收录的论文 UniMC，其只需要将标签构造成为选项即可，不需要构造复杂的Prompt工程，现已开源，详情请看https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/unimc
