### ISSUE TITLE
希望可以开源 continue training 相关代码

### ISSUE THREAD

**Issue by Amazing-J** [IDEA-CCNL/Fengshenbang-LM#127]
希望可以尽快开源 DeBerta continue training 的相关代码。感谢

**Comment by Amazing-J** [comment]
官方的 DeBerta 代码会特别吃 CPU 内存，不适用预训练任务

**Comment by GGGGGGXY** [comment]
预训练代码可以参考我的分支
https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/dev/gaoxinyu/fengshen/examples/pretrain_erlangshen_deberta_v2
预训练完整数据未开源，但是可以参照数据处理逻辑，详情见：
https://github.com/IDEA-CCNL/fs_datasets
预训练预料基于wudao_180g:
https://github.com/IDEA-CCNL/fs_datasets/tree/master/wudao_180g

**Comment by Amazing-J** [comment]
有几个问题哈
1. 直接运行 sh 文件，从头初始化一个 Deberta 模型，那用的是什么 tokenizer，sh 文件里面也没用参数指定呀？词表用的是什么？
2. 如果我想 continuing training 的话，  需要怎么操作？是否修改.sh文件里面的 load_ckpt_path 参数即可？

**Comment by Amazing-J** [comment]
IDEA-CCNL/PretrainCorpusDemo   这个参考文件路径在哪里？

**Comment by GGGGGGXY** [comment]
> 有几个问题哈
> 
> 1. 直接运行 sh 文件，从头初始化一个 Deberta 模型，那用的是什么 tokenizer，sh 文件里面也没用参数指定呀？词表用的是什么？
> 2. 如果我想 continuing training 的话，  需要怎么操作？是否修改.sh文件里面的 load_ckpt_path 参数即可？

tokenizer在源码中可以看到是跟模型存在一起的，在workspace下面有tokenizer的具体配置。模型权重、词表等都可以在huggingface找到。

load_ckpt_path是训练中异常中断、重启的时候用的，如果要做继续训练，你只需要修改源码，源码是重新初始化了一个deberta模型，你只需要改成load已经训练的权重就可以了，比如用DebertaV2ForMaskedLM.from_pretrained的方式加载权重。
