### ISSUE TITLE
BUS error

### ISSUE THREAD

**Issue by Gavingx** [IDEA-CCNL/Fengshenbang-LM#129]
你好，请问finetuning至少需要多少内存呢？我尝试运行finetune_classification.sh，但是一直报如下错误：
`fengshen/examples/classification/finetune_classification.sh: line 74: 28016 Bus error               (core dumped) python3 $SCRIPT_PATH $options`。网上有人说这个问题是因为内存不够。可是我看硬盘还有670G。

**Comment by GGGGGGXY** [comment]
硬盘670G应该没啥问题，内存这个需要考虑具体的模型大小，如果是30亿左右的模型的话，估计需要80G内存，小模型对内存需求应该不大

**Comment by Gavingx** [comment]
> 硬盘670G应该没啥问题，内存这个需要考虑具体的模型大小，如果是30亿左右的模型的话，估计需要80G内存，小模型对内存需求应该不大

好的，感谢。已经解决了。原因是容器启动的时候共享内存的数值设置不太够。通过设置--shm-size参数解决了这个问题
