### ISSUE TITLE
提供一个封神榜docker镜像

### ISSUE THREAD

**Issue by ganzhiruyi** [IDEA-CCNL/Fengshenbang-LM#131]
最近一些试用反馈了环境问题，可以提供一个运行封神榜所需要安装环境的docker镜像和示例，方便使用。

**Comment by Gavingx** [comment]
> 最近一些试用反馈了环境问题，可以提供一个运行封神榜所需要安装环境的docker镜像和示例，方便使用。

这样挺好的，跑fine tuning的代码。显存都没占满，报CUDA OUT OF MEMORY

**Comment by ganzhiruyi** [comment]
Done. https://github.com/IDEA-CCNL/Fengshenbang-LM/pull/134
