### ISSUE TITLE
请教专家老师一个关于batch_sampler中consumed_samples参数的问题

### ISSUE THREAD

**Issue by scuyjzh** [IDEA-CCNL/Fengshenbang-LM#138]
在学习使用官方提供的二郎神1.3B模型预训练脚本[pretrain_erlangshen_base.sh](https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/pretrain_erlangshen_bert/pretrain_erlangshen_base.sh)时，其中replace_sampler_ddp设置为False，那么在train_dataloader中将会使用自定义的batch_sampler，我看到是通过get_custom_sampler这一函数实现的，其中consumed_samples这个参数的意义和计算逻辑是怎么样的呢？它指的是已经经过训练的样本数量吗？我看到它在模型开始训练时值输出为0，不知道这块有没有问题？自己看代码有点没搞懂，希望可以请假一下专家老师
![image](https://user-images.githubusercontent.com/12816241/192180652-315de783-584f-4af0-8558-99e735402cbe.png)
![image](https://user-images.githubusercontent.com/12816241/192180673-389cec24-6e2b-4510-8242-a933947d9b99.png)
![image](https://user-images.githubusercontent.com/12816241/192180634-0c7f2acf-e20f-47eb-bec5-fbadc00aa9e5.png)

**Comment by GGGGGGXY** [comment]
是的，这个是记录已经消费了多少samples，如果不记录的话，在从ckpt断点重启的时候dataloader会重头开始遍历，与预期不符
