### ISSUE TITLE
燃灯系列的 Randeng-Pegasus-523M-Summary-Chinese 模型是不是长传错了？实际效果和文档不符

### ISSUE THREAD

**Issue by LYL-HNU** [IDEA-CCNL/Fengshenbang-LM#143]
`
from transformers import PegasusForConditionalGeneration
from tokenizers_pegasus import PegasusTokenizer

model = PegasusForConditionalGeneration.from_pretrained("IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese")
tokenizer = PegasusTokenizer.from_pretrained("IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese")

text = "据微信公众号“界面”报道，4日上午10点左右，中国发改委反垄断调查小组突击查访奔驰上海办事处，调取数据材料，并对多名奔驰高管进行了约谈。截止昨日晚9点，包括北京梅赛德斯-奔驰销售服务有限公司东区总经理在内的多名管理人员仍留在上海办公室内"
inputs = tokenizer(text, max_length=1024, return_tensors="pt")

# Generate Summary
summary_ids = model.generate(inputs["input_ids"])
tokenizer.batch_decode(summary_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

# 宣传输出: 反垄断调查小组突击查访奔驰上海办事处，对多名奔驰高管进行约谈
# 实际输出：老鼠老鼠老鼠老鼠老鼠老鼠老鼠
`

效果远不如base 版本，甚至不如微调版本
模型上传错误？

**Comment by dongxqm** [comment]
![图片](https://user-images.githubusercontent.com/107237598/194689553-22f4c081-26e4-43af-bf11-209756359dc0.png)

能否给一下具体的调用环境信息，python 版本， transformer 版本，jieba 版本

**Comment by dongxqm** [comment]
@LYL-HNU 我这边环境如下所示：
Python 3.8.10

**Comment by LYL-HNU** [comment]
> @LYL-HNU 我这边环境如下所示： python 3.8.10 transformers 4.20.1 jieba 0.42.1

我用这个配置重新试了下，还是遇到这个问题。输出还是老鼠老鼠老鼠
![1665564882406](https://user-images.githubusercontent.com/32981640/195297815-e451548e-42a9-4fd3-b038-34d8944d7a68.png)


我发现在tokenizer_pegasus.py 手动设置了分词器，但是huggingface上没有上传，不知道是不是这个原因。

![1665564835465](https://user-images.githubusercontent.com/32981640/195297622-1257a1f6-1b2c-4f63-8d8e-443a49b05eca.png)

**Comment by dongxqm** [comment]
关于 tokenizer 的问题：

**Comment by dongxqm** [comment]
@LYL-HNU 昨天使用你下载的模型在我这验证没有问题哈，发现你下载的文件里面的有些配置文件还是很久之前的版本，没有更新，可按照 hugging facce 上最新的文件版本进行更新，验证结果如下所示：
