### ISSUE TITLE
关于推理输出的问题

### ISSUE THREAD

**Issue by cave-crypto** [IDEA-CCNL/Fengshenbang-LM#146]
您好，我最近正在使用您开源的模型做小样本分类任务，但是在推理结果中，有时还会遇到两个entity_type都会判定为1的情况，我想通过score来取，但是并不是每一个字段都有score。请问是否有参数可控，来强制输出每个字段的score？

例子：
{entity_type: '0', 'label': 0, 'entity_list': []}
{entity_type: '1', 'label': 1, 'entity_list': [], 'score':0.1123412}
{entity_type: '2', 'label': 1, 'entity_list': []}
{entity_type: '3', 'label': 0, 'entity_list': []}

如上所示，在1,2中，模型都判定为1，此时我想通过score来获取最终结果，但是 entity_type = 2的字典中，没有输出score。 请问你们是如何处理这种情况的

**Comment by suolyer** [comment]
目前没有提供参数来控制这个输出，ubert 更倾向于做抽取任务。对于小样本分类任务，推荐你使用我们最新开源的模型 UniMC，https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/unimc/
