### ISSUE TITLE
是否有计划开源AIWIN比赛相关的其他代码

### ISSUE THREAD

**Issue by Faith-Uchiha** [IDEA-CCNL/Fengshenbang-LM#153]
感觉有点简略额，其他的代码有计划开源吗？ 比如说数据处理的代码，预训练的代码，构建三张表的代码，以及模型融合部分的。。

主要想通过这个项目学习小样本比赛的整个流程hh

**Comment by ganzhiruyi** [comment]
是说UBert模型吗？可以描述清楚一些。如果是UBert的话[UBert](https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/ubert)已经把格式交代得很清楚了，可以尝试对自己的数据进行处理，实在遇到问题我们也可以之后补下脚本。另外这个标题不是很友好，希望可以修改。

**Comment by Faith-Uchiha** [comment]
> 是说UBert模型吗？可以描述清楚一些。如果是UBert的话[UBert](https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/ubert)已经把格式交代得很清楚了，可以尝试对自己的数据进行处理，实在遇到问题我们也可以之后补下脚本。另外这个标题不是很友好，希望可以修改。

标题已修改，sorry，我没有别的意思，只是真诚的想来学习，标题给您带来不适很抱歉。

我想问的不是Ubert，我是看了你们在知乎上写的文章之后对该方案比较感兴趣，希望从头做一遍这个比赛，所以想问问有没有不那么“开箱即用”的代码。

比如您在文章中说到的“3维的表” ，与之相关的处理代码是否会开源
![image](https://user-images.githubusercontent.com/26248309/197383183-ad050e6e-54f0-49b4-9d7d-1ad4eed11402.png)

再如文中提到的“我们限制第3维的长度固定为 10 ，如果表一个任务的样本表情少于 10，我们就进行 pad。然后计算loss的时候 mask掉就可以了，如果超过 10 了，就保留正样本，对负样本进行随机采样。满足10样本即可”

我想要了解随机采样部分的代码是怎么写的？

如果不方便开源，也没关系

祝好！

**Comment by suolyer** [comment]
hi～，@Faith-Uchiha；相关代码已开源，即 [Ubert](https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/ubert)，开箱即用参见这个 [https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/ubert](https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/ubert)。你所说的数据预处理主要在我们的代码[modeling_ubert](https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/models/ubert/modeling_ubert.py)中的第56行，你可以详细看看

https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/42f0ef3e58ce18b9e45e92999eccefebaa3fd905/fengshen/models/ubert/modeling_ubert.py#L56

ubert目前主要针对抽取任务，对于分类任务的小样本场景，我们最新  开源 了一个 unimc 模型，如有需要可以查阅[https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/unimc](https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/unimc)，
