### ISSUE TITLE
ValueError:

### ISSUE THREAD

**Issue by cingtiye** [IDEA-CCNL/Fengshenbang-LM#16]
非常感谢开源。有几个问题请教一下：

1、在加载下面代码时，发现程序报错了，但是将`AutoTokenizer`替换为`BertTokenizer`程序就对了！

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(Path('E://work//Dialog//checkpoints//Zhouwenwang-110M'))
```
**ValueError: unable to parse E:\work\Dialog\checkpoints\Zhouwenwang-110M\tokenizer_config.json as a URL or as a local path**

transformers版本为 4.15.0
Python 版本为 3.7
torch 版本为 1.7.1

请问是版本不对还是缺少`tokenizer_config.json`文件

2、我发现110M和1.3B两个模型`config.json`中`model_type`不一样前者是`megatron-bert`，后者是`bert`。但是加载的都是`RoFormerModel`，所以是不是不用关心`model_type`。但是发现在`pretraining.py`中，对于下面的代码
```python
model_mlm_type = {'bert': BertForMaskedLM,
                  'roformer': RoFormerForMaskedLM,
                  'megatron': MegatronBertForMaskedLM}
```
不同的`model_type`所采用的`MaskedLM`是不一样的。

3、对于给的例程，我发现`predict`的时候是用当前词去预测下一个词的，但是`pretraining`的时候是将当前位置用`[MASK]`代替，然后让模型对于source和target采用不同的attention_mask方式去预测的。这样的话`predict`个`pretraining`是不一至的，模型在`predict`的时候又怎么能够去根据当前词去预测下一个词呢？请问我是不是什么地方理解的不对。因为用下面的例程可以有很好的预测结果，因此不明白`1.3B`这个模型具体是怎么训练的？

```python
from model.roformer.modeling_roformer import RoFormerModel
from transformers import BertTokenizer
import torch
import numpy as np
from pathlib import Path

sentence = '清华大学位于'
max_length = 32

tokenizer = BertTokenizer.from_pretrained(Path('E://work//Dialog//checkpoints//Zhouwenwang-1.3B'))
model = RoFormerModel.from_pretrained(Path('E://work//Dialog//checkpoints//Zhouwenwang-1.3B'))
# model = model.to(torch.device('cuda'))
for i in range(max_length):
    encode = torch.tensor(
        [[tokenizer.cls_token_id]+tokenizer.encode(sentence, add_special_tokens=False)]).long()
    # encode = encode.to(torch.device('cuda'))
    print(encode)
    logits = model(encode)[0]
    logits = torch.nn.functional.linear(
        logits, model.embeddings.word_embeddings.weight)
    logits = torch.nn.functional.softmax(
        logits, dim=-1).cpu().detach().numpy()[0]
    sentence = sentence + \
        tokenizer.decode(int(np.random.choice(logits.shape[1], p=logits[-1])))
    if sentence[-1] == '。':
        break
print(sentence)
```

非常期待得到您的回复！

**Comment by suolyer** [comment]
感谢关注我们的开源计划，回复如下：
1、AutoTokenizer会根据model_type去寻找对应的Tokenizer。而HuggingFace的megatron-bert没有对应的Tokenizer。
2、这里的示例是为了简单区分不同的模型需要加载不同的模型结构，与config.json上的model_type有所区别
3、Zhouwenwang模型采用的是混合预训练，即BERT任务和GPT任务同时训练（有点类似[UniLM](https://readpaper.com/paper/2971274815)），所以其既可以做NLU任务也可以做NLG任务，目前暂未提供混合pretraining的示例。

**Comment by cingtiye** [comment]
你好，非常感谢你的回答！

还有两个问题想请教一下您：
1、请问周文王这个模型在做NLU时，起始和结束的字符分别是什么？句子和句子之间是否添加了额外的特殊字符？是否和BERT一样是`[CLS]...[SEP]...[SEP]`？
2、请问周文王在做NLG时，起始和结束的字符分别是什么？句子和句子之间是否添加了额外的特殊字符？是否和BERT一样是`[CLS]...[SEP]...[SEP]`？

非常期待得到您的回复！

**Comment by suolyer** [comment]
> 你好，非常感谢你的回答！
> 
> 还有两个问题想请教一下您： 1、请问周文王这个模型在做NLU时，起始和结束的字符分别是什么？句子和句子之间是否添加了额外的特殊字符？是否和BERT一样是`[CLS]...[SEP]...[SEP]`？ 2、请问周文王在做NLG时，起始和结束的字符分别是什么？句子和句子之间是否添加了额外的特殊字符？是否和BERT一样是`[CLS]...[SEP]...[SEP]`？
> 
> 非常期待得到您的回复！


NLU任务基本与BERT的一致，所不同的是本模型的token_type需要全部设置为0，即使是句子对任务也是全设置为0。NLG任务的输入形式也是与BERT一致，一般不用接结束token[SEP]，只接 [CLS]。例如我们想要做续写任务时，输入句子为”【CLS】深圳是一座“。这里需要注意的是NLG任务token_type需要全部设置为1。

**Comment by cingtiye** [comment]
您好，还有两个地方不太理解，还请再指教一下：

1、周文王1.3B这个模型采用24层的transformer，在做NLU时，相当于直接将最后一层（连接到pool后）连接相应的任务；在做NLG时，相当于直接连接了`self.decoder = nn.Linear(config.hidden_size, config.vocab_size, bias=False)`，但是参数是共享`Embedding`的，而没有额外去在transformer的输出端加入以下代码，请问预训练也是这样做的吗？
```python
        self.dense = nn.Linear(config.hidden_size, config.hidden_size)
        if isinstance(config.hidden_act, str):
            self.transform_act_fn = ACT2FN[config.hidden_act]
        else:
            self.transform_act_fn = config.hidden_act
        self.LayerNorm = nn.LayerNorm(config.hidden_size, eps=config.layer_norm_eps)
```

2、在计算`attention_scores`时，`attention_mask`是个`torch.BoolTensor`，而没有向BERT将`attention_mask`用一个极小的数替代，下面的代码就相当于对`attention_mask`中`True`的部分加1，对`False`的部分加0啊，**这一点着实难以理解**。
```python
        attention_scores = attention_scores / math.sqrt(self.attention_head_size)
        if attention_mask is not None:
            # Apply the attention mask is (precomputed for all layers in RoFormerModel forward() function)
            attention_scores = attention_scores + attention_mask
```

**Comment by suolyer** [comment]
1、是的，预训练时也没有增加一层decode
2、你的理解没问题，是我这里写错了，已经修正。
