### ISSUE TITLE
Randeng-T5-784M-MultiTask-Chinese 的使用问题？

### ISSUE THREAD

**Issue by ScottishFold007** [IDEA-CCNL/Fengshenbang-LM#161]
请问，除了文本分类任务， 情感分析，新闻分类，意图识别，自然语言推理，多项选择，指代消解，抽取式阅读理解，实体识别，关键词抽取，生成式摘要的使用prompt是什么呢？该模型应该如何在其他任务上使用？谢谢~

**Comment by wxj630** [comment]
你好，我们已经更新了huggingface上的readme，给出了不同任务的promot；

**Comment by wxj630** [comment]
如果您对于怎么预训练Randeng-T5模型或者想在自己的下游任务中微调Randeng模型，欢迎使用[Fengshenbang-LM](https://github.com/IDEA-CCNL/Fengshenbang-LM/)项目，这里提供了完整的示例：

[预训练](https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/pretrain_t5)
[微调](https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/mt5_summary)

**Comment by hbwliao** [comment]
您好，我简单测试了一下hugging上IDEA-CCNL/Randeng-T5-784M-QA-Chinese模型的示例，在尝试的过程中遇到了些问题。请问对transformers和torch的版本有什么具体的适配要求吗。

**Comment by ScottishFold007** [comment]
你本地环境跑的吧？我colab跑没问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月2日(周三) 晚上7:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IDEA-CCNL/Fengshenbang-LM] Randeng-T5-784M-MultiTask-Chinese 的使用问题？ (Issue #161)




 
您好，我简单测试了一下hugging上IDEA-CCNL/Randeng-T5-784M-QA-Chinese模型的示例，在尝试的过程中遇到了些问题。请问对transformers和torch的版本有什么具体的适配要求吗。
