### ISSUE TITLE
UniMC全量数据微调效果

### ISSUE THREAD

**Issue by JaheimLee** [IDEA-CCNL/Fengshenbang-LM#167]
请问UniMC在下游任务做全量数据finetune的话，效果跟传统finetune比怎么样啊

**Comment by suolyer** [comment]
全量数据，目前我们只测评了13亿模型的结果，如下，基本优于直接 finetune
|                                            | AFQMC | TNEWS1.1 | IFLYTEK | OCNLI | CMNLI | WSC1.1 | CSL   | CHID  | C3    |
|--------------------------------------------|-------|----------|---------|-------|-------|--------|-------|-------|-------|
| RoBERTa-Base                               | 74.06 | 57.5     | 60.36   | 74.3  | 79.73 | 83.48  | 85.37 |    -   |     -  |
| RoBERTa-Large                              | 74.88 | 58.79    | 61.52   | 77.7  | 81.4  | 89.14  | 86    |    -   |    -   |
| [Erlangshen-MegatronBert-1.3B](https://huggingface.co/IDEA-CCNL/Erlangshen-MegatronBert-1.3B) 「Finetuning」              | 76.08 | 59.38    | 62.34   | 79.14 | 81    | 92.43  | 87.2  | 84.65 | 86.77 |
| [Erlangshen-UniMC-MegatronBERT-1.3B-Chinese](https://huggingface.co/IDEA-CCNL/Erlangshen-UniMC-MegatronBERT-1.3B-Chinese) | 77.09 | 60.4     | 62.67   | 83.05 | 84.76 | 93.74  | 87.67 | 85.93 | 86.54 |
