### ISSUE TITLE
CHID这种成语选择填空问题该如何构建呢？

### ISSUE THREAD

**Issue by BD-MF** [IDEA-CCNL/Fengshenbang-LM#168]
您好
请问像CHID这种成语选择填空问题该如何构建呢？ 因为对于每条样本的候选成语不是一样的，如何抽象它们的标签呢？

**Comment by suolyer** [comment]
对于chid成语填空任务，可以构造如下
```json
{
	"texta": "而苹果提升旧手机的回购价,也让果粉__,如果选择以旧换新,这确实能薅官方羊毛,但如果没准备入手iPhone12,将与“福利”擦肩而过。如果你是iPhone11用户,你会怎么选?",
	"textb": "",
	"question": "请问填空处（__）选择哪一个成语最合适？",
	"choice": ["神不守舍", "指指点点", "知易行难", "左右为难", "不咸不淡", "束手无策", "疏而不漏"],
	"answer": "左右为难",
	"label": 3,
	"id": 1734
}
```
也可以用把成语所在的句子放到选项里
```json
{
	"texta": "本土PE如山创投的丁世平告诉记者___往往投资比较快、退出和套现也比较快，所以，退出环节出问题就会影响到他们的运行。和通管理国际有限公司的投资总监杜伟明也认为，金融风暴会对创投行业的每一个环节都会产生影响，因此也将导致创投策略的改变。",
	"textb": "",
	"question": "",
	"choice": ["那些私募性质的VC和PE由于比较祸不单行，",
                           "那些私募性质的VC和PE由于比较急功近利，",
                           "那些私募性质的VC和PE由于比较瓜熟蒂落，", 
                           "那些私募性质的VC和PE由于比较画蛇添足，", 
                           "那些私募性质的VC和PE由于比较本末倒置，", 
                           "那些私募性质的VC和PE由于比较因噎废食，", 
                           "那些私募性质的VC和PE由于比较约定俗成，",
                           "那些私募性质的VC和PE由于比较不伦不类，", 
                           "那些私募性质的VC和PE由于比较芒刺在背，", 
                           "那些私募性质的VC和PE由于比较不合时宜，"],
	"answer": "那些私募性质的VC和PE由于比较急功近利，",
	"label": 1,
	"id": "#idiom577158#",
	"text_id": 1,
	"line_id": 0
}
```

**Comment by BD-MF** [comment]
非常感谢您的解答，这是在inference阶段的构建，请问在模型多任务训练阶段，这个任务是如何构建的呢，CHID每条样本有7个候选成语选项，每个成语选项都不相同，请问这个问题如何解呢？

**Comment by suolyer** [comment]
> 非常感谢您的解答，这是在inference阶段的构建，请问在模型多任务训练阶段，这个任务是如何构建的呢，CHID每条样本有7个候选成语选项，每个成语选项都不相同，请问这个问题如何解呢？

训练阶段和inference 阶段是一致的，训练阶段每条样本不区分任务类型、选项的数量、具体选项内容。也就是训练阶段你的每条数据只要保证 包含 texta、textb、question、choice、label等这些字段即可，而不需要每条样本的 choice 都保证一摸一样。

**Comment by BestSongEver** [comment]
非常荣幸能在刚学习zero-shot时接触到Fengshenbang-LM这么好的工具，感谢@suolyer。
想请教您：我想学习和测试UniMC模型的zero-shot能力（就比如说完整复现其在Clue Zero-shot单子的成绩），是需要对每个数据集都参考xxxxx/unimc/example.py进行数据的重新构建吧
那每个数据集需要构建多少条数据用于训练呢？还是说要把整个训练集、验证集、测试集（例如BUSTM数据集的unlabeled.json中有4251条数据，dev.json有32条数据，test.json有2000条数据）都重新构建？如果是都重新构建，那和全部标注一遍差不多，工作量非常大吧。请问可以提供构建好的数据文件吗。
谢谢！
