### ISSUE TITLE
关于中文tokenizer的疑问

### ISSUE THREAD

**Issue by miaodog** [IDEA-CCNL/Fengshenbang-LM#169]
你好，我在https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/pretrain_t5/pretrain_randeng_t5_large.sh
中发现使用了这样的参数设置
![image](https://user-images.githubusercontent.com/110814689/198836186-e86ace21-ff8e-4305-8195-301ee6a1c60c.png)
请问这sentencepiece_cn.model和sentencepiece_cn_keep_tokens.json两个文件是如何来的呢？

**Comment by ganzhiruyi** [comment]
你好，首先这部分代码是在mt5的基础上继续在中文语料上训练，同时只保留mt5词表里的中英文部分。
sentencepiece_cn.model这个就是开源模型里对应的https://huggingface.co/IDEA-CCNL/Randeng-T5-77M/blob/main/spiece.model,这是在mt5原有的sentencepiece模型里只保留了中英文的部分。
sentencepiece_cn_keep_tokens.json你是可以通过记载sentencepiece_cn.model获得的。
具体代码见
https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/pretrain_t5/pretrain_t5.py#L30
