### ISSUE TITLE
二郎神LongFormer是否可以用Transformers加载?

### ISSUE THREAD

**Issue by yangjingyuan** [IDEA-CCNL/Fengshenbang-LM#173]
**【transformers加载方式】**
from transformers import LongformerModel
model = LongformerModel.from_pretrained("IDEA-CCNL/Erlangshen-Longformer-110M")

**【fengshen加载方式】**
from fengshen import LongformerModel   
model = LongformerModel.from_pretrained("IDEA-CCNL/Erlangshen-Longformer-110M")

请问这两种加载方式有什么区别呢？

**Comment by suolyer** [comment]
主要区别在于位置编码，我们这里实现的 longformer 使用的是 Roformer 的旋转位置编码，而 HuggingFace实现的是 绝对位置编码

**Comment by yangjingyuan** [comment]
明白了，那就是不能用transformers的LongFomer, 否则Embedding参数初始化会异常

**Comment by haonit** [comment]
那么是不是说，你们的longformer其实是模型结构使用的是longformer，位置编码使用的是refomer的位置编码。这样做是可以达到更好的效果么？
