### ISSUE TITLE
UniMC loss问题

### ISSUE THREAD

**Issue by JaheimLee** [IDEA-CCNL/Fengshenbang-LM#174]
https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/ecade734940e1363577afcf7c5d699d98651f90b/fengshen/models/unimc/modeling_unimc.py#L329
您好，请问这里mask_loss不是包含了cls_loss吗，为什么还要再加一遍啊？

**Comment by suolyer** [comment]
> https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/ecade734940e1363577afcf7c5d699d98651f90b/fengshen/models/unimc/modeling_unimc.py#L329
> 
> 
> 您好，请问这里mask_loss不是包含了cls_loss吗，为什么还要再加一遍啊？

你好，unimc 包含两个loss，一个是 MaskLM 任务用来还原 yes 或 no 的 loss，另一个是横向比较每个选项之间哪个 yes 的 score 最大的 loss
