### ISSUE TITLE
where is the "diffusers" module

### ISSUE THREAD

**Issue by Arvid-pku** [IDEA-CCNL/Fengshenbang-LM#178]
Thank you for your fancy work(https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1)!
But when I want to try it, I can't find the "diffusers" in your demo code in the readme.
Should I install any other rep?
Looking forward to your reply.

**Comment by ganzhiruyi** [comment]
You can get information from https://huggingface.co/docs/diffusers/main/en/index

**Comment by Arvid-pku** [comment]
Got it! Thank you for your reply!
