### ISSUE TITLE
Taiyi-Stable-Diffusion-1B-Chinese-v0.1   CUDA out of memory

### ISSUE THREAD

**Issue by qiezikuangge** [IDEA-CCNL/Fengshenbang-LM#180]
用的GTX1660Ti，6G的显存，大小512*512，1张图片就超显存了吗？stable-difffusion两张都可以啊

**Comment by ganzhiruyi** [comment]
参考半精度这里，3090上实测一张图片512*512 4G左右，https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1#%E5%8D%8A%E7%B2%BE%E5%BA%A6-half-precision-fp16-cuda
