### ISSUE TITLE
机器之心过来的，请问是否有WebUI版本或者结构和sd/novel兼容的版本

### ISSUE THREAD

**Issue by catalystfrank** [IDEA-CCNL/Fengshenbang-LM#181]
方便试用和扩大影响力。多谢。
因为SD和novel已经演化到具备自己的UI了，webui循环的debug，impaint很重要。
现在是视频制作用sd的webui已经满足基本制作需求了，中国元素少也是一个大问题，希望咱们项目尽快解决

**Comment by ganzhiruyi** [comment]
可以参考https://github.com/IDEA-CCNL/Fengshenbang-LM/issues/186
