### ISSUE TITLE
OSError: /path/ does not appear to have a file named config.json

### ISSUE THREAD

**Issue by Arvid-pku** [IDEA-CCNL/Fengshenbang-LM#185]
need help
I download all the files of Taiyi from https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1/tree/main and use the same directory structure.
But when I use the command: `pipe = StableDiffusionPipeline.from_pretrained("/home/path/taiyi/").to("cuda")`, I get the error:
`OSError: /home/path/ does not appear to have a file named config.json`
Is there any config I should download?
looking forward to your reply

**Comment by ganzhiruyi** [comment]
It maybe the diffuers update, what‘s your diffuers and transformers version? My load is good, here is my versions:
diffusers               0.3.0
transformers            4.19.2

**Comment by ganzhiruyi** [comment]
you can refer https://github.com/IDEA-CCNL/stable-diffusion-webui/blob/master/README.md , I have writen a readme for taiyi webui
