### ISSUE TITLE
使用你们代码打QBQTC比赛，得分只有65.592

### ISSUE THREAD

**Issue by huangjiaheng** [IDEA-CCNL/Fengshenbang-LM#192]

**Comment by GGGGGGXY** [comment]
使用模型IDEA-CCNL/Erlangshen-DeBERTa-v2-97M-Chinese，在dev集上acc 0.7288，只是简单跑跑非最终效果。辛苦同学自己check下自己的使用方式
<img width="412" alt="image" src="https://user-images.githubusercontent.com/15215819/200811304-841a51a4-fd25-46da-9c96-5f3e9685696e.png">

<img width="936" alt="image" src="https://user-images.githubusercontent.com/15215819/200811171-5f07e4e1-ad89-40c6-be7a-edf57d7f42da.png">
