### ISSUE TITLE
how to use IDEA-CCNL/Erlangshen-TCBert-110M-Sentence-Embedding-Chinese

### ISSUE THREAD

**Issue by yyht** [IDEA-CCNL/Fengshenbang-LM#196]
hi, I am wondering the usage of this model: IDEA-CCNL/Erlangshen-TCBert-110M-Sentence-Embedding-Chinese,
could you provide some example code and explanmantion?

**Comment by pskun** [comment]
> hi, I am wondering the usage of this model: IDEA-CCNL/Erlangshen-TCBert-110M-Sentence-Embedding-Chinese, could you provide some example code and explanmantion?

hi, we are writing a paper and will release our codes and examples soon.

**Comment by pskun** [comment]
> hi, I am wondering the usage of this model: IDEA-CCNL/Erlangshen-TCBert-110M-Sentence-Embedding-Chinese, could you provide some example code and explanmantion?

Hi, yyts, sorry to have kept you waiting.
We have released our [paper](https://arxiv.org/abs/2211.11304) and [example codes](https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/tcbert) for finetuning.
As for how to construct sentence embedding, you can refer to our paper.
