### ISSUE TITLE
finetune_taiyi_stable_diffusion   BertModel loaded pretrained model

### ISSUE THREAD

**Issue by yangzhipeng1108** [IDEA-CCNL/Fengshenbang-LM#200]
File "finetune.py", line 38, in __init__
    self.text_encoder = BertModel.from_pretrained

transformers.file_utils.EntryNotFoundError: 404 Client Error: Entry Not Found for url: https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1/resolve/main/config.json

**Comment by sunfvrise** [comment]
+1

**Comment by sunfvrise** [comment]
> +1

BertModel源码中对Hugging face模型的兼容性问题，强制引用/reslove/main/路径。暂时可以将模型下载到本地路径解决。

**Comment by ganzhiruyi** [comment]
> File "finetune.py", line 38, in **init** self.text_encoder = BertModel.from_pretrained
> 
> transformers.file_utils.EntryNotFoundError: 404 Client Error: Entry Not Found for url: https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1/resolve/main/config.json

这个是他版本兼容问题，可以尝试升级transformers>=4.24.0, diffusers>=0.7.2

**Comment by yangzhipeng1108** [comment]
OK，thanks

**Comment by yangzhipeng1108** [comment]
OK，thanks
