### ISSUE TITLE
资源问题

### ISSUE THREAD

**Issue by WGS-note** [IDEA-CCNL/Fengshenbang-LM#203]
https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/finetune_taiyi_stable_diffusion

hi，全精度要显存是26G以上，我微调用四个卡跑ddp模式，为什么还会显存不足呢？

**Comment by WGS-note** [comment]
四个卡，每个卡都是16G

**Comment by ganzhiruyi** [comment]
> https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/finetune_taiyi_stable_diffusion
> 
> hi，全精度要显存是26G以上，我微调用四个卡跑ddp模式，为什么还会显存不足呢？

ddp是每张卡上都会保存一份模型参数、梯度和optimizer状态，不会自动给你做模型并行，所以你如果是全精度每张卡还是要26G，建议按照我们的指引尝试fp16+deepspeed
