### ISSUE TITLE
中文stable diffusion训练

### ISSUE THREAD

**Issue by winnechan** [IDEA-CCNL/Fengshenbang-LM#205]
原始的stable diffusion在训练的时候clip text encoder是冻结的，但是太乙在训练的时候连同text encoder一起训练，问一下这样训练是否稳定？

**Comment by Weifeng-Chen** [comment]
> 原始的stable diffusion在训练的时候clip text encoder是冻结的，但是太乙在训练的时候连同text encoder一起训练，问一下这样训练是否稳定？

learning rate不能太大，太大就会崩。

**Comment by Weifeng-Chen** [comment]
> 



> > > 原始的stable diffusion在训练的时候clip text encoder是冻结的，但是太乙在训练的时候连同text encoder一起训练，问一下这样训练是否稳定？
> > 
> > 
> > learning rate不能太大，太大就会崩。
> 
> 那如果也同样冻结text encoder只训练unet生成器，性能会下降很多吗

还没试，目前做的比较省资源，后续有资源了可以试试。

**Comment by winnechan** [comment]
> 



> > 
> 
> > > > 原始的stable diffusion在训练的时候clip text encoder是冻结的，但是太乙在训练的时候连同text encoder一起训练，问一下这样训练是否稳定？
> > > 
> > > 
> > > learning rate不能太大，太大就会崩。
> > 
> > 
> > 那如果也同样冻结text encoder只训练unet生成器，性能会下降很多吗
> 
> 还没试，目前做的比较省资源，后续有资源了可以试试。

我理解冻结text encoder不需要计算该部分的梯度，应该训练时更节省显存吧。。。
