### ISSUE TITLE
在自有数据上finetune Taiyi-Stable-Diffusion

### ISSUE THREAD

**Issue by Life-0-1** [IDEA-CCNL/Fengshenbang-LM#207]
感觉提供优秀的中文stable diffusion模型。我试图在自有数据上finetune的时候，遇到些问题，希望能够被解答。
在 finetune.sh 中：
1. TORCH_EXTENSIONS_DIR=${ROOT_DIR}/torch_extendsions 目录下应该放什么？
2. 如果想要启用deepspeed，CONFIG_JSON="$MODEL_ROOT_DIR/${MODEL_NAME}.ds_config.json"， 该文件应该如何配置，能否提供一个你们finetune时候使用的文件呢？

**Comment by ganzhiruyi** [comment]
1. 这个是存放torch需要用到的lib包，程序会自动编译，创建这个目录就ok了
2. 这个也是程序自动生成的，跑起来之后你就会在目录下发现这个配置文件，我们已经最大程度简化deepspeed配置，只保留一些用户平时可能用到的配置，如果你需要自定义一些deepspeed的配置，可以参考https://github.com/microsoft/DeepSpeed ，然后在finetune.sh里增加配置就ok了。

**Comment by Life-0-1** [comment]
> 1. 这个是存放torch需要用到的lib包，程序会自动编译，创建这个目录就ok了
> 2. 这个也是程序自动生成的，跑起来之后你就会在目录下发现这个配置文件，我们已经最大程度简化deepspeed配置，只保留一些用户平时可能用到的配置，如果你需要自定义一些deepspeed的配置，可以参考https://github.com/microsoft/DeepSpeed ，然后在finetune.sh里增加配置就ok了。

非常感谢！

**Comment by winnechan** [comment]
@ganzhiruyi 你好，我使用了脚本https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/finetune_taiyi_stable_diffusion/finetune.sh用demo_dataset里的数据进行训练，但是在内存200G以及显存22G的情况下还是CUDA OOM了，请问要怎么解决这个问题？感觉deepspeed并没有起作用，当前版本deepspeed为fengshen/requirements.txt里的0.5.10

**Comment by winnechan** [comment]
> @ganzhiruyi 你好，我使用了脚本https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/finetune_taiyi_stable_diffusion/finetune.sh 用demo_dataset里的数据进行训练，但是在内存200G以及显存22G的情况下还是CUDA OOM了，请问要怎么解决这个问题？感觉deepspeed并没有起作用，当前版本deepspeed为fengshen/requirements.txt里的0.5.10

I resolved the problem by updating deepspeed to 0.6.0 and offload the optimier to cpu.
