### ISSUE TITLE
太乙微调后的使用问题

### ISSUE THREAD

**Issue by WGS-note** [IDEA-CCNL/Fengshenbang-LM#212]
Hi，https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/finetune_taiyi_stable_diffusion/finetune.py，基于这个链接，以deepspeed+ddp微调后保存了检查点ckpt，请问：如何使用微调保存后的ckpt去生成图片？

**Comment by GGGGGGXY** [comment]
在ckpt的目录下有hf_out_开头的文件夹，那个是huggingface结构的模型，可以直接用这个目录给huggingface加载
例如
`
from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained(
    "../workspace/taiyi-stablediffusion/hf_out_19_1060",
    torch_dtype=torch.bfloat16,
).to("cuda")
pipe.enable_xformers_memory_efficient_attention()

while True:
    prompt = input()
    with torch.inference_mode():
        image = pipe(prompt, guidance_scale=7.5).images[0]
        image.save(f"pic/dm_generate.png")

`

**Comment by ZHongshuang** [comment]
xformers一直都装不上，
测试的时候去掉pipe.enable_xformers_memory_efficient_attention()对推理的结果会有影响吗

**Comment by GGGGGGXY** [comment]
> xformers一直都装不上，
> 测试的时候去掉pipe.enable_xformers_memory_efficient_attention()对推理的结果会有影响吗

没影响，  enable_xformers_memory_efficient_attention可以加速推理，去掉推理慢一点

**Comment by zhangyifanaaa** [comment]
按照您提供的方法我进行了图片的生成，但是每张图片上面都是马赛克，而且程序一直在运行，这个是什么原因呀
![image]( #https://user-images.githubusercontent.com/100468029/205541745-b1688d34-cb37-47ed-8490-3ab8fcfc7cb9.png)，可以帮我看看吗

**Comment by zhangyifanaaa** [comment]
> @GGGGGGXY 您好，我这边遇到了同样的问题，fintune过后的效果很差。fintune用的数据集样例如下： ![0000000000](https://user-images.githubusercontent.com/116628807/208571477-2b591295-dd59-47c4-a22f-456da1999d25.jpg) promot为： 新疆天然和田玉吊坠18K金镶嵌阳绿碧玉项链水滴蛋面
> 
> 使用相同的promot产生的结果为： ![diaozhui](https://user-images.githubusercontent.com/116628807/208571622-e60d888e-0f37-46f6-885b-1a8d8a9f65ac.png)

我可以加您一下联系方式吗，问您几个问题

**Comment by zhangyifanaaa** [comment]
可以加您一下吗，问您几个问题，我的QQ：2711981219
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IDEA-CCNL/Fengshenbang-LM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月20日(星期二) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IDEA-CCNL/Fengshenbang-LM] 太乙微调后的使用问题 (Issue #212)





 
@GGGGGGXY 您好，我这边遇到了同样的问题，fintune过后的效果很差。fintune用的数据集样例如下：
 
 promot为： 新疆天然和田玉吊坠18K金镶嵌阳绿碧玉项链水滴蛋面
 
使用相同的promot产生的结果为：

**Comment by Nipi64310** [comment]
> 在ckpt的目录下有hf_out_开头的文件夹，那个是huggingface结构的模型，可以直接用这个目录给huggingface加载 例如
> 
> ```
> from diffusers import StableDiffusionPipeline
> import torch
> 
> pipe = StableDiffusionPipeline.from_pretrained(
>     "../workspace/taiyi-stablediffusion/hf_out_19_1060",
>     torch_dtype=torch.bfloat16,
> ).to("cuda")
> pipe.enable_xformers_memory_efficient_attention()
> 
> while True:
>     prompt = input()
>     with torch.inference_mode():
>         image = pipe(prompt, guidance_scale=7.5).images[0]
>         image.save(f"pic/dm_generate.png")
> ```

Hi @GGGGGGXY , when I use the deepspeed zero stage3 strategy to train taiyi sd on a single machine with multiple gpus, the parameters saved in taiyi-stablediffusion-1B/hf_out_x_xx  are only those of a single gpu, and the weight in taiyi-stablediffusion-1B/ckpt can be load normally after conversion. How to make taiyi-stablediffusion-1B/hf_out_x_xx save complete parameters as well?

**Comment by leijuzi** [comment]
> > xformers一直都装不上，
> > 测试的时候去掉pipe.enable_xformers_memory_efficient_attention()对推理的结果会有影响吗
> 
> 没影响， enable_xformers_memory_efficient_attention可以加速推理，去掉推理慢一点

求问下大佬，安装上 xformers后，直接报错了，torch都import不进来。没有安装之前是好的，报错：libcublas.so.11: undefined symbol: cublasLtGetStatusS tring, version libcublasLt.so.11
