### ISSUE TITLE
finetune taiyi-stable-diffusion时怎么将fp32改成fp16呢？

### ISSUE THREAD

**Issue by Norman-Ou** [IDEA-CCNL/Fengshenbang-LM#213]
因使用fp32 + deepspeed + ddp训练超显存了，所以想要改成半精度。相应文件/fengshen/examples/finetune_taiyi_stable_diffusion

**Comment by winnechan** [comment]
@Norman-Ou 你好，你尝试过使用脚本https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/finetune_taiyi_stable_diffusion/finetune.sh微调taiyi吗？我在200G内存和22G显存的情况下还是出现了CUDA OOM的情况，请问你遇到过吗？

**Comment by Norman-Ou** [comment]
@winnechan  我的是160GB内存，48GB显存，deepspeed，batchsize=1，precision 16，没改接口前是可以跑通的

**Comment by winnechan** [comment]
@Norman-Ou 羡慕，48G显存应该不需要deepspeed也能放下？还是很感谢你的回复，我再问问别人fp16+deepspeed的解决方案（叹气摇头
