### ISSUE TITLE
about  windows  pip install --editable ./ error

### ISSUE THREAD

**Issue by zhanghongyong123456** [IDEA-CCNL/Fengshenbang-LM#214]
![image](https://user-images.githubusercontent.com/48466610/203503620-d092591b-6726-4cd0-9150-609f7aeae3db.png)
是否安装了deepspeed项目

**Comment by ganzhiruyi** [comment]
会安装https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/setup.py里面的package，包括deepspeed

**Comment by dongluyang** [comment]
please refer to this link https://www.toutiao.com/article/7271252191200248360/, i give a solution for resolving above problem in windows
