### ISSUE TITLE
微调可否提供一个 colab 版本？

### ISSUE THREAD

**Issue by ringhyacinth** [IDEA-CCNL/Fengshenbang-LM#215]
使用目前的脚本一直报错

**Comment by wanng-ide** [comment]
good idea! we are working on it.

**Comment by flufy3d** [comment]
cool

**Comment by ganzhiruyi** [comment]
> 使用目前的脚本一直报错

https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/finetune_taiyi_stable_diffusion/finetune_taiyi_stable_diffusion_example.ipynb

**Comment by wanng-ide** [comment]
云端是有问题的，但是本地应该ok，因为colab给的内存和显存太小了。跑不动一个bs。
