### ISSUE TITLE
negative prompt 对于 Taiyi-Stable-Diffusion-1B-Chinese-v0.1 好像并没有作用

### ISSUE THREAD

**Issue by svjack** [IDEA-CCNL/Fengshenbang-LM#227]
如题。如果想要利用 negative_prompt 来加强 [Taiyi-Stable-Diffusion-1B-Chinese-v0.1](https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1) 的效果 经过测试 好像并不能。

是特殊的模型训练方式导致的 还是有一些其他的使用方法？

**Comment by ganzhiruyi** [comment]
目前我们测试了一些比较有用的negative prompt，文本控制的能力还在优化中。
