### ISSUE TITLE
Installing fengshen framework colab版本少這個

### ISSUE THREAD

**Issue by catgrassgb6** [IDEA-CCNL/Fengshenbang-LM#229]
!pip install tensorboard
!pip install jieba

我不確定是不是沒寫到還是說本來自己就要記得裝
from IPython.display import clear_output

!pip install pytorch_lightning
!pip install transformers
!pip install deepspeed
!pip install diffusers
!pip install datasets
!pip install accelerate
改
from IPython.display import clear_output

!pip install pytorch_lightning
!pip install transformers
!pip install deepspeed
!pip install diffusers
!pip install datasets
!pip install accelerate
!pip install tensorboard
!pip install jieba

(我是新手 我不敢確定

**Comment by Desein-Yang** [comment]
感谢补充！是我们从头安装的环境文档不够完善。
