### ISSUE TITLE
使用 Docker 运行带 Web UI 的太乙模型应用 / Use Docker to simply run Taiyi(太乙) with Web UI

### ISSUE THREAD

**Issue by soulteary** [IDEA-CCNL/Fengshenbang-LM#230]
Hello maintainers, 👋

Thanks to the IDEA official team for bringing this fun and interesting model project. 🍻

I've created a project to tell people, how to use the docker to simple and quickly run the **Taiyi** model, AI application with Stable Diffusion Web UI.

link: https://github.com/soulteary/docker-stable-diffusion-taiyi

I hope to solve the various problems accumulated in the current project that cannot run **Taiyi** due to environmental problems.

-----

项目维护团队，你好鸭，👋

感谢 IDEA 模型团队，带来的这个好玩有趣的模型项目。 🍻

我创建了一个开源项目，里面演示了如何使用 docker 来简单快速地运行带 Web UI 的 **太乙** 模型 AI 应用程序。

项目地址：https://github.com/soulteary/docker-stable-diffusion-taiyi

希望，它能解决当前项目中 issue 里积累的，由于环境问题无法运行模型或者 Web UI 的各种问题。

**Comment by ganzhiruyi** [comment]
> Hello maintainers, 👋
> 
> Thanks to the IDEA official team for bringing this fun and interesting model project. 🍻
> 
> I've created a project to tell people, how to use the docker to simple and quickly run the **Taiyi** model, AI application with Stable Diffusion Web UI.
> 
> link: https://github.com/soulteary/docker-stable-diffusion-taiyi
> 
> I hope to solve the various problems accumulated in the current project that cannot run **Taiyi** due to environmental problems.
> 
> 项目维护团队，你好鸭，👋
> 
> 感谢 IDEA 模型团队，带来的这个好玩有趣的模型项目。 🍻
> 
> 我创建了一个开源项目，里面演示了如何使用 docker 来简单快速地运行带 Web UI 的 **太乙** 模型 AI 应用程序。
> 
> 项目地址：https://github.com/soulteary/docker-stable-diffusion-taiyi
> 
> 希望，它能解决当前项目中 issue 里积累的，由于环境问题无法运行模型或者 Web UI 的各种问题。

感谢对我们项目的关注和建议，非常好的docker环境教程，由于目前太乙依赖的diffuser库还在更新，这里我们采取的是requirements来帮助配置环境，后续也会参考你的项目来更新我们的docker，我已经置顶了这个issue方便其他使用docker的用户能够很方便地跑起来太乙stable diffusion。
