### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

### ISSUE THREAD

**Issue by catgrassgb6** [IDEA-CCNL/Fengshenbang-LM#232]
![image](https://user-images.githubusercontent.com/104978239/206858536-201bc985-f231-47e7-ba96-399c0396bf73.png)

![image](https://user-images.githubusercontent.com/104978239/206858519-a18d7bf5-ef1b-47d0-90a0-88e0574a666e.png)

使用網址會出現的問題
![image](https://user-images.githubusercontent.com/104978239/206858513-8e017743-14dc-4684-a488-d95d23b9d210.png)

使用檔案方法會出現的問題

我不知道怎麼解決 我一直找不到方法 希望有人可以幫我

**Comment by muximuxi** [comment]
请问，问题解决了吗？我也出现了这个错误，是完全按照说明里执行的，是demo 的数据格式不对吗？

**Comment by catgrassgb6** [comment]
> 请问，问题解决了吗？我也出现了这个错误，是完全按照说明里执行的，是demo 的数据格式不对吗？

檔案格式問題，看你要慢慢找還是全部重用 （txt那邊的
