### ISSUE TITLE
 windows 操作系统使用 stable-diffusion-webui 报错AttributeError: module 'os' has no attribute 'statvfs'

### ISSUE THREAD

**Issue by xuYuan-chen1988** [IDEA-CCNL/Fengshenbang-LM#237]
操作系统：window10
报错场景：web端可访问，填好参数最终生成图片的时候
![image](https://user-images.githubusercontent.com/56064909/207324552-a2025a3c-2097-4373-8507-1f1e31c3b7ca.png)

**Comment by ganzhiruyi** [comment]
windows 目前我们没有进行尝试，看报错是package问题，可以google下

**Comment by oheheMKII** [comment]
修改\stable-diffusion-webui\modules\images.py 422行
 max_length = os.statvfs(dir_name).f_namemax
为固定值 max_length = 255
