### ISSUE TITLE
使用clip_finetune_flickr.py以及flickr30k-CNA进行训练，test正常，训练在第一个step后立刻loss很大、acc很低，同时loss不再下降

### ISSUE THREAD

**Issue by vincezengqiang** [IDEA-CCNL/Fengshenbang-LM#241]
感谢作者，非常优秀的工作！
在使用clip_finetune_flickr.py以及flickr30k-CNA进行训练，在trainer.test后显示准确率：
image_to_text r1:0.728, r5:0.952, r10:0.976
text_to_image r1:0.558, r5:0.8284, r10:0.9028
但是在trainer.fit进行第一个step之后，
loss=3.930, acc=0.00195
并且之后的训练指标一直这样，loss不再下降、acc不再上升。
请问，这种情况可能是哪里出的问题呢？
感谢回答！

**Comment by vincezengqiang** [comment]
排查后发现是pytorch1.8版本的adamw实现存在bug，可修复这个bug或切换至1.9即可正常训练

**Comment by MonaZJU** [comment]
我在torch2.0.1上也遇到了这个问题   请问你正常训练的torch  transformers  pytorch_lightning版本是什么    怎么保存模型才能在他的推理demo里正常使用呢
