### ISSUE TITLE
多卡推理问题

### ISSUE THREAD

**Issue by WGS-note** [IDEA-CCNL/Fengshenbang-LM#245]
Hi，我正在使用燃灯 https://huggingface.co/IDEA-CCNL/Randeng-TransformerXL-5B-Deduction-Chinese

一条句子预测的时候，老是CUDA内存不足，我的卡是16G显存。

请问：怎么样开启多卡推理预测？DP、DDP训练我知道，但是多卡推理就不会了，望赐教，谢谢！

**Comment by ganzhiruyi** [comment]
如果你单卡 bs=1就OOM，多卡推理其实不能帮助你，这个时候更好的做法是用fp16,bf16，cpuoffload，模型并行的方案进行优化，建议最快的方案是用更大的显存
