### ISSUE TITLE
The zhouwenwang model can't finetune with FP16

### ISSUE THREAD

**Issue by fangd123** [IDEA-CCNL/Fengshenbang-LM#25]
The error is as follows:
```bash
  File "roformer/modeling_roformer.py", line 333, in forward
    attention_scores = attention_scores.masked_fill(attention_mask,
RuntimeError: value cannot be converted to type at::Half without overflow: -1e+08
```
What should I do to solve this problem ?

**Comment by suolyer** [comment]
> The error is as follows:
> 
> ```shell
>   File "roformer/modeling_roformer.py", line 333, in forward
>     attention_scores = attention_scores.masked_fill(attention_mask,
> RuntimeError: value cannot be converted to type at::Half without overflow: -1e+08
> ```
> 
> What should I do to solve this problem ?

 bert默认的mask加上的一个小值是-1e5，而我这里加上的-1e8。数值过小，超过半精度的范围，因此有这个问题。可修改如下

` attention_scores = attention_scores.masked_fill(
                attention_mask, value=torch.tensor(-1e5))`

**Comment by fangd123** [comment]
ok thank you！
