### ISSUE TITLE
悟空数据集的使用

### ISSUE THREAD

**Issue by jammyWolf** [IDEA-CCNL/Fengshenbang-LM#251]
看了你们https://huggingface.co/IDEA-CCNL/Taiyi-CLIP-Roberta-large-326M-Chinese  这个项目，请问一下 wukong_release里面没有进行train和validation的切分，想问下 这个划分有什么技巧么还是随意划分即可

**Comment by ganzhiruyi** [comment]
wukong有一个专门的wukong50k用于测试，用的这个数据集
