### ISSUE TITLE
finetune taiyi sd  - ema

### ISSUE THREAD

**Issue by Nipi64310** [IDEA-CCNL/Fengshenbang-LM#252]
How should [ema](https://github.com/huggingface/diffusers/blob/8874027efc2619df2e8b2b567396573b5e9a2ee6/examples/text_to_image/train_text_to_image.py#L269) be used when using deepspeed zero stage3 strategy to finetune taiyi sd?

**Comment by Nipi64310** [comment]
`https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/1513010a8c187040f32b211c1d14ab9c6e6659cb/fengshen/examples/finetune_taiyi_stable_diffusion/finetune.py#L90`
This line contains an error, it should be `text_encoder.parameters()`.

**Comment by ganzhiruyi** [comment]
> https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/1513010a8c187040f32b211c1d14ab9c6e6659cb/fengshen/examples/finetune_taiyi_stable_diffusion/finetune.py#L90

Thanks for the issue， fix it
