### ISSUE TITLE
Ubert的示例代码，进行实体识别，结果是空的

### ISSUE THREAD

**Issue by LANSEYOUYUMOWANG** [IDEA-CCNL/Fengshenbang-LM#254]
运行环境：
python                        3.8.15
torch                           1.8.2+cu111
transformers               4.25.1
pytorch-lightning       1.8.5.post0
运行的代码如下
![45de4acec6e9f2285ee591e5177706e](https://user-images.githubusercontent.com/36221128/210289733-35d234de-5eb3-4a01-b4a8-782e3a0c19e3.png)
实体识别结果为：

![38106fb962484bd019661e740576faf](https://user-images.githubusercontent.com/36221128/210289785-4c7a7c01-1395-41db-a3cd-22db836012c6.png)

**Comment by suolyer** [comment]
这个主要是transformers版本的原因，高版本的transformers的tokenizer会有点不一样。我的是 transformers==4.20.0，你可以参考我这个试试看

**Comment by LANSEYOUYUMOWANG** [comment]
将transformers版本恢复到4.20.0报如下错误：
![image](https://user-images.githubusercontent.com/36221128/210514257-872eee77-ae48-4529-8756-0a293ac0e303.png)
![image](https://user-images.githubusercontent.com/36221128/210514478-fd06bc0f-d04b-4bfb-b5f5-284bc8657118.png)

**Comment by LANSEYOUYUMOWANG** [comment]
您好，麻烦您帮我看下，我将transformers的版本恢复到4.20.0，报如下错误






yuhao
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IDEA-CCNL/Fengshenbang-LM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月4日(星期三) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IDEA-CCNL/Fengshenbang-LM] Ubert的示例代码，进行实体识别，结果是空的 (Issue #254)





 
这个主要是transformers版本的原因，高版本的transformers的tokenizer会有点不一样。我的是 transformers==4.20.0，你可以参考我这个试试看

**Comment by suolyer** [comment]
你copy这个例子的代码运行试试看https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/ubert/example.py

**Comment by LANSEYOUYUMOWANG** [comment]
yuhao
***@***.***



&nbsp;
您好，我使用您发的https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/ubert/example.py下的代码还是报错，报错信息如下：




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IDEA-CCNL/Fengshenbang-LM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月4日(星期三) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IDEA-CCNL/Fengshenbang-LM] Ubert的示例代码，进行实体识别，结果是空的 (Issue #254)





 
你copy这个例子的代码运行试试看https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/ubert/example.py

**Comment by suolyer** [comment]
你把本地缓存的hf模型删除了，或者你手动下载https://huggingface.co/IDEA-CCNL/Erlangshen-Ubert-110M-Chinese/tree/main。 模型文件，然后把https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/ubert/example.py#L13第13行代码    args.pretrained_model_path = 'IDEA-CCNL/Erlangshen-Ubert-110M-Chinese'改成你手动下载的模型文件路径。你试试看

**Comment by LANSEYOUYUMOWANG** [comment]
您好，我重新尝试后，运行example.py的代码报如下错误，麻烦您帮忙看下：







yuhao
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IDEA-CCNL/Fengshenbang-LM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月4日(星期三) 晚上6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IDEA-CCNL/Fengshenbang-LM] Ubert的示例代码，进行实体识别，结果是空的 (Issue #254)





 
你把本地缓存的hf模型删除了，或者你手动下载https://huggingface.co/IDEA-CCNL/Erlangshen-Ubert-110M-Chinese/tree/main。 模型文件，然后把&nbsp;args.pretrained_model_path = 'IDEA-CCNL/Erlangshen-Ubert-110M-Chinese'改成你手动下载的模型文件路径。你试试看

**Comment by suolyer** [comment]
> 

你好！请问是报什么错呢，我这里看不见，你能贴个截图或者copy报错信息过来吗

**Comment by LANSEYOUYUMOWANG** [comment]
您好，运行example.py的代码报如下错误：
![image](https://user-images.githubusercontent.com/36221128/210907308-6a690df1-dd93-4bfc-bb97-8151213360d3.png)

**Comment by LANSEYOUYUMOWANG** [comment]
您好，我按照您说得将 transformers安装为4.20.0版本，pytorch-lightning安装为1.6.0版本，运行成功，但是仍热识别出来为空，还的麻烦您帮我看下是什么原因，谢谢
![image](https://user-images.githubusercontent.com/36221128/212004158-ce3926db-9b18-4116-9bcd-7d6380eebfe5.png)
![image](https://user-images.githubusercontent.com/36221128/212004223-7fb43e67-ca2c-4a2c-849b-e935914dc64f.png)
![image](https://user-images.githubusercontent.com/36221128/212004306-264307df-72a5-4133-b384-2f67151b2027.png)
