### ISSUE TITLE
关于finetune

### ISSUE THREAD

**Issue by Peterchen111** [IDEA-CCNL/Fengshenbang-LM#260]
我应该如何在自定义文本分类数据集上进行finetune，有详细教程吗

**Comment by lishuzhen97** [comment]
你好，有解决嘛，我也想试试在预训练的模型在自己的数据集上finetune试试

**Comment by ganzhiruyi** [comment]
参考下这个https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/classification/demo_classification_afqmc_roberta.sh
