### ISSUE TITLE
ImportError: cannot import name 'UbertPiplines' from 'fengshen'

### ISSUE THREAD

**Issue by LeiShenVictoria** [IDEA-CCNL/Fengshenbang-LM#264]
运行ubert命名实体识别的样例代码时报错：ImportError: cannot import name 'UbertPiplines' from 'fengshen'

-------
import argparse
from fengshen import UbertPiplines

total_parser = argparse.ArgumentParser("TASK NAME")
total_parser = UbertPiplines.piplines_args(total_parser)
args = total_parser.parse_args()

args.pretrained_model_path = "IDEA-CCNL/Erlangshen-Ubert-110M-Chinese"

test_data=[
    {
        "task_type": "抽取任务", 
        "subtask_type": "实体识别", 
        "text": "这也让很多业主据此认为，雅清苑是政府公务员挤对了国家的经适房政策。", 
        "choices": [ 
            {"entity_type": "小区名字"}, 
            {"entity_type": "岗位职责"}
            ],
        "id": 0}
]

model = UbertPiplines(args)
result = model.predict(test_data)
for line in result:
    print(line)

**Comment by lwcode** [comment]
I have the same problem, how to fix it?@LeiShenVictoria

**Comment by lwcode** [comment]
Oh, it is misspelling in the demo, not the "UbertPiplines", it's actually "UbertPipelines".
