### ISSUE TITLE
cannot import name UbertPiplines

### ISSUE THREAD

**Issue by MonkeyTB** [IDEA-CCNL/Fengshenbang-LM#268]
https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/15991122307b6490659e93bf4d5bba8fd5c23754/fengshen/examples/ubert/example.py#L2

提示没有UbertPiplines，自动补全发现有UbertPipelines，想问问是我安装有问题还是怎么回事？

**Comment by czhcc** [comment]
应该是改为UbertPipelines了，原名称少了个“e”

**Comment by MonkeyTB** [comment]
好像不是，不知道怎么解释，jupyter里面运行会报错，linux下运行就没问题，就很神奇

**Comment by czhcc** [comment]
在那个example.py里，用
 from fengshen import UbertPiplines 
都会报错，改为

 from fengshen import UbertPipelines 
就没错了，连里面的方法敢要改为pipelines_args
