### ISSUE TITLE
燃灯系列-T5问答模型微调 代码跑不通

### ISSUE THREAD

**Issue by Stxr** [IDEA-CCNL/Fengshenbang-LM#269]
地址： fengshen/examples/qa_t5/README.md

**Comment by LeiShenVictoria** [comment]
@hejunqing Hi, the finetuning code for t5-qa model cannot work

**Comment by hejunqing** [comment]
What are the errors and your environment, and which script did you run?

**Comment by Stxr** [comment]
> What are the errors and your environment, and which script did you run?
in `fengshen/examples/qa_t5/README.md`
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/18367238/224602481-075189b1-2130-4b43-9b2b-8863fef24880.png">
This script has obvious errors. Where does this "self" come from?

**Comment by Mr-IT007** [comment]
The Usage part can not work

**Comment by hejunqing** [comment]
@Mr-IT007 your code is ok. These are all hyper-parameters.  I will update my Usage for clarity, Thx!

**Comment by Stxr** [comment]
你的邮箱我已收到，谢谢！                                                            唐湘润
