### ISSUE TITLE
使用IDEA-CCNL/Randeng-Pegasus-238M-Summary-Chinese速度慢

### ISSUE THREAD

**Issue by wanglaiqi** [IDEA-CCNL/Fengshenbang-LM#271]
速度比较慢怎么优化

**Comment by Desein-Yang** [comment]
1. 简单加速可判断是否使用 KV cache、generate 参数更小的 num_beam、控制生成长度等
2. 进一步的参考其他 transformers 的推理加速方案，比如 fast transformer 、int8 量化等
