### ISSUE TITLE
YuyuanQA-GPT2-3.5B模型可以给出中文回答吗？

### ISSUE THREAD

**Issue by tangyipeng100** [IDEA-CCNL/Fengshenbang-LM#272]
似乎YuyuanQA-GPT2-3.5B模型只能给出英文回答，是否可以得到中文回答？谢谢。

**Comment by Zimix0** [comment]
YuyuanQA这个模型是针对医疗领域来训练的一个问答模型，这个模型的预训练语料是英文的，许多论文文献，也主要是英文为主。finetune也是用的英文问答，所以暂时对英文的问答支持的比较好。或者您也可以用中文医疗问答数据finetune一下试试看效果。
