### ISSUE TITLE
燃灯系列-mT5 做多任务训练时， model.generate中不存在force_words_ids这个参数

### ISSUE THREAD

**Issue by BD-MF** [IDEA-CCNL/Fengshenbang-LM#273]
cond_output = self.model.generate(
            input_ids=batch['input_ids'],
            attention_mask=batch['attention_mask'],
            force_words_ids=batch['force_words_ids'],
            num_beams=2,
        )
https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/f121ae50023e18e3550c32a84ea83a274bce6948/fengshen/examples/pretrain_t5/finetune_t5.py#L66

**Comment by BD-MF** [comment]
*** TypeError: forward() got an unexpected keyword argument 'force_words_ids'

**Comment by hsdzhao** [comment]
how to do
