### ISSUE TITLE
Maybe some errors in code?

### ISSUE THREAD

**Issue by winnechan** [IDEA-CCNL/Fengshenbang-LM#275]
https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/f121ae50023e18e3550c32a84ea83a274bce6948/fengshen/examples/stable_diffusion_dreambooth/train.py#L78-L81

Should be as follows?

```
self.text_encoder.requires_grad_(False) 
...
self.unet.requires_grad_(False) 
```

**Comment by GGGGGGXY** [comment]
is the same
