### ISSUE TITLE
燃灯摘要项目没有“fengshen”模块

### ISSUE THREAD

**Issue by ucas010** [IDEA-CCNL/Fengshenbang-LM#279]
hi，dear大佬

按照此link：https://huggingface.co/IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese
操作，不能复现，bug如下：
>>> from transformers import PegasusForConditionalGeneration
>>> from tokenizers_pegasus import PegasusTokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/Fengshenbang-LM/fengshen/examples/pegasus/tokenizers_pegasus.py", line 1, in <module>
    from fengshen.examples.pegasus.data_utils import (
ModuleNotFoundError: No module named 'fengshen'
could U pls help me ?
thx

**Comment by ZhouZineng** [comment]
ModuleNotFoundError: No module named 'fengshen'这个我也遇到了但是下面提供的链接是空的这个"fengshen"model要怎么安装

**Comment by Peineng** [comment]
上述链接失效，请参考https://github.com/IDEA-CCNL/Fengshenbang-LM/issues/177，重点是到Fengshenbang-LM的folder (有setup.py)下，用”pip3 install --editable .“ 进行安装即可。Good luck!

**Comment by Hubotcoder** [comment]
> 上述链接失效，请参考[https://github.com/IDEA-CCNL/Fengshenbang-LM/issues/177，重点是到Fengshenbang-LM的folder](https://github.com/IDEA-CCNL/Fengshenbang-LM/issues/177%EF%BC%8C%E9%87%8D%E7%82%B9%E6%98%AF%E5%88%B0Fengshenbang-LM%E7%9A%84folder) (有setup.py)下，用”pip3 install --editable .“ 进行安装即可。Good luck!

还是不行，报错
Collecting deepspeed>=0.5.10 (from fengshen==0.0.1)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/73/11/14f424b21eddaf2c339e0c149ec0a11159ab5eb7340303d311ddb47e9689/deepspeed-0.11.1.tar.gz (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 8.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-48_cw8n1\deepspeed_c2a8ad8fd66a4c01812fc892b0d9d943\setup.py", line 100, in <module>
          cuda_major_ver, cuda_minor_ver = installed_cuda_version()
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-48_cw8n1\deepspeed_c2a8ad8fd66a4c01812fc892b0d9d943\op_builder\builder.py", line 41, in installed_cuda_version
          assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
                 ^^^^^^^^^^^^^^^^^^^^^
      AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
