### ISSUE TITLE
megatron_t5 转成 燃灯 T5

### ISSUE THREAD

**Issue by WenzhengZhang** [IDEA-CCNL/Fengshenbang-LM#283]
请问你们用Megatron_LM 框架预训练完的checkpoint是怎么转成燃灯T5的？ Megatron_LM 中的T5模型[megatron_t5.py](https://github.com/NVIDIA/Megatron-LM/blob/285068c8108e0e8e6538f54fe27c3ee86c5217a2/megatron/model/t5_model.py) 和燃灯T5的框架是不一样的，所以你们应该是自己写了script去转化的吗？

**Comment by miaodog** [comment]
> 请问你们用Megatron_LM 框架预训练完的checkpoint是怎么转成燃灯T5的？ Megatron_LM 中的T5模型[megatron_t5.py](https://github.com/NVIDIA/Megatron-LM/blob/285068c8108e0e8e6538f54fe27c3ee86c5217a2/megatron/model/t5_model.py) 和燃灯T5的框架是不一样的，所以你们应该是自己写了script去转化的吗？

有同样的疑问+1，想知道如果基于原生的megatron lm框架训练T5，产出的模型如何导出为huggingface可以直接加载的？

**Comment by ganzhiruyi** [comment]
> 请问你们用Megatron_LM 框架预训练完的checkpoint是怎么转成燃灯T5的？ Megatron_LM 中的T5模型[megatron_t5.py](https://github.com/NVIDIA/Megatron-LM/blob/285068c8108e0e8e6538f54fe27c3ee86c5217a2/megatron/model/t5_model.py) 和燃灯T5的框架是不一样的，所以你们应该是自己写了script去转化的吗？

是的。
