### ISSUE TITLE
悟道纯文本数据集训练pretrain_bert，loss多少算正常

### ISSUE THREAD

**Issue by hujunchao** [IDEA-CCNL/Fengshenbang-LM#290]
最近在悟道纯文本数据集训练pretrain_bert，loss多少算正常，我这边好像一直在5以上

**Comment by GGGGGGXY** [comment]
2以下

**Comment by GGGGGGXY** [comment]
不过这个也跟具体的任务构建方式有关系，比如用wwm的方式，或者mask的比例不一样，不同任务上不具备太大的参考价值
