### ISSUE TITLE
二郎神系列-Example示例问题

### ISSUE THREAD

**Issue by cason0126** [IDEA-CCNL/Fengshenbang-LM#291]
Example 中的    from fengshen import UbertPiplines  是否应该为 UbertPiplines  -> UbertPipleines。
![image](https://user-images.githubusercontent.com/35160064/221079609-448fc05a-f9a5-4447-9f0f-95e5c206a7d5.png)

**Comment by ykallan** [comment]
`from fengshen.models.ubert import UbertPipelines

total_parser = argparse.ArgumentParser("抽取任务")
total_parser.add_argument("--pretrained_model_path", default="Erlangshen-Ubert-330M-Chinese")
total_parser = UbertPipelines.pipelines_args(total_parser)
args = total_parser.parse_args()`
我目前是这样使用的，而且还要把项目的源码改一下
`class UbertPipelines:
    @staticmethod
    def pipelines_args(parent_args):
        total_parser = parent_args.add_argument_group("pipelines args")
        # total_parser.add_argument(
        #     '--pretrained_model_path', default='IDEA-CCNL/Erlangshen-Ubert-110M-Chinese', type=str)
        total_parser.add_argument('--output_save_path',
                                  default='./predict.json', type=str)
`
