### ISSUE TITLE
显存占用问题

### ISSUE THREAD

**Issue by aph-asic** [IDEA-CCNL/Fengshenbang-LM#294]
你好，我在对闻仲进行微调的时候，观察到显存的占用是逐步上升的，特别是在经历过一轮epoch后，显存占用不稳定，请问是什么原因呢，望解答，谢谢！

**Comment by aph-asic** [comment]
请问会不会是哪个部分造成了显存泄露呢

**Comment by GGGGGGXY** [comment]
是看的监控还是在代码里把torch显存占用打出来了，torch显存释放后不会及时还给sys，而是做预留，在空间里看到的像是内存一直在增长一样
