### ISSUE TITLE
TransfoXLDenoiseModel 转换为 huggingface

### ISSUE THREAD

**Issue by nghuyong** [IDEA-CCNL/Fengshenbang-LM#298]
请教一下，我想用huggingface库来加载TransfoXLDenoiseModel系列模型（IDEA-CCNL/Randeng-TransformerXL-1.1B-Paraphrasing-Chinese， IDEA-CCNL/Randeng-Transformer-1.1B-Denoise）应该用`GPT-2`吗？

**Comment by ganzhiruyi** [comment]
目前transformers还没有实现，模型介绍里有说，先用fengshen/models里的模型加载https://huggingface.co/IDEA-CCNL/Randeng-TransformerXL-1.1B-Paraphrasing-Chinese
