### ISSUE TITLE
Erlangshen-Roberta-110M-NLI 相同句子判定为不相关或CONTRADICTION 

### ISSUE THREAD

**Issue by Kiode** [IDEA-CCNL/Fengshenbang-LM#299]
在用数据集做测试的过程中，发现有好几个样本，两段话完全相同，但是被判定为CONTRADICTION 或 NEUTRAL，请问是什么原因？

两个示例如下，在huggingface的api上直接尝试也是如此。

”这是一个很棘手的问题，因为涉及到你的感受和你和你男友之间的关系。首先，你需要考虑你是否愿意原谅你男友的行为。这可能需要你花时间来思考你的感受，以及你和你男友之间的关系是否值得继续。如果你决定原谅你男友，你可能希望讨论这件事，并确保你男友能够理解你的感受，并且愿意接受责任。如果你决定不原谅你男友，你可能希望寻求支持，并考虑在不同的情况下继续你的生活。无论你的决定如何，请记住，你有权利做出自己觉得最好[SEP]这是一个很棘手的问题，因为涉及到你的感受和你和你男友之间的关系。首先，你需要考虑你是否愿意原谅你男友的行为。这可能需要你花时间来思考你的感受，以及你和你男友之间的关系是否值得继续。如果你决定原谅你男友，你可能希望讨论这件事，并确保你男友能够理解你的感受，并且愿意接受责任。如果你决定不原谅你男友，你可能希望寻求支持，并考虑在不同的情况下继续你的生活。无论你的决定如何，请记住，你有权利做出自己觉得最好“

“失恋是一件很难受的事情，很多人都会感到悲伤、沮丧、孤独和无助。如果你正在经历失恋，那么你很可能会有这样的疑问："我放不下的到底是什么？"其实，放不下的可能是很多东西，比如对方的陪伴、爱、温暖和关心。也可能是你们之间的回忆、承诺和计划。也可能是你对未来的憧憬、希望和承诺。无论是什么，都是很正常的，因为在恋爱关系中，你和对方都会投入很多感情、时间和精力。当这段关系结束时，你很可能会感到悲伤和失落，因为[SEP]失恋是一件很难受的事情，很多人都会感到悲伤、沮丧、孤独和无助。如果你正在经历失恋，那么你很可能会有这样的疑问："我放不下的到底是什么？"其实，放不下的可能是很多东西，比如对方的陪伴、爱、温暖和关心。也可能是你们之间的回忆、承诺和计划。也可能是你对未来的憧憬、希望和承诺。无论是什么，都是很正常的，因为在恋爱关系中，你和对方都会投入很多感情、时间和精力。当这段关系结束时，你很可能会感到悲伤和失落，因为”

**Comment by Kiode** [comment]
1. 遮阳伞的材料和品质：确保遮阳伞材料品质良好，能承受风吹日晒。[SEP]1. 遮阳伞的材料和品质：确保遮阳伞材料品质良好，能承受风吹日晒。 

短文本也出错了

**Comment by suolyer** [comment]
模型只是在通用NLI任务上进行了测试，你可以用自己的语料继续fientune，效果会好点
