### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16BF, lda, b, CUDA_R_16BF, ldb, &fbeta, c, CUDA_R_16BF, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)

### ISSUE THREAD

**Issue by zhenzi0322** [IDEA-CCNL/Fengshenbang-LM#301]
我在尝试训练`Fengshenbang-LM/fengshen/examples/finetune_taiyi_stable_diffusion/`。但是失败了。

我执行的命令如下：
```
./finetune.sh
```

下面是我的执行日志: 
[finetune.log](https://github.com/IDEA-CCNL/Fengshenbang-LM/files/10939865/finetune.log)

**Comment by GGGGGGXY** [comment]
显卡不是3090ti或者a100吧，  不支持bfloat，把精度修改成fp16
