### ISSUE TITLE
闻仲模型的字典怎么都是英文的？不是中文的嘛？

### ISSUE THREAD

**Issue by 447428054** [IDEA-CCNL/Fengshenbang-LM#307]
@ganzhiruyi @hejunqing @Randolph-zeng @schwgHao 
如题
![image](https://user-images.githubusercontent.com/35593767/225899259-340b00f6-8b94-4209-8339-9f4f5c815d8d.png)

full_tokenizer = tokenization_bert.BertTokenizer(vocab_file='../Wenzhong-GPT2-3.5B/vocab.json')

print(full_tokenizer.tokenize("今天天气真不错"))

> ['[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]']

**Comment by ganzhiruyi** [comment]
你的tokenizer不对，按照huggingface的使用示例来。https://huggingface.co/IDEA-CCNL/Wenzhong2.0-GPT2-3.5B-chinese

**Comment by wangpeng138375** [comment]
最简单的中文bpe都没做，gpt中文模型可惜了
