### ISSUE TITLE
finetune_wenzhong.sh和finetune_wenzhong.py缺数据样例？

### ISSUE THREAD

**Issue by mikeda100** [IDEA-CCNL/Fengshenbang-LM#308]
我在研读 finetune_wenzhong.py这个文件，里面用到的GPT2QADataModel, 来自于 fengshen.data.task_dataloader.medicalQADataset 。
但是现在找不到具体的数据。原始数据不知道到哪里去下载。
看程序中的意思是在wuziwei和gaoxinyu两位朋友的目录中。

而 finetune_wenzhong.sh脚本中的：train.txt, valid.txt 等又与上述task_dataloader.medicalQADataset中的描述不一致。

btw我的目标是理解他们是如何在闻仲上做medicalQA的（特别是数据集的准备）fine-tuning。 先学习如何复现。再将其代码从QA fine-tuning改为语句学习的fine-tuning。

现在的问题在于：github上的代码路径和数据路径不对，跑不通。

似乎 finetune_wenzhong.sh脚本指向一些数据来源，而研读 finetune_wenzhong.py里面用到的GPT2QADataModel, 来自于 fengshen.data.task_dataloader.medicalQADataset 也指向一些数据来源。但是两者都没有数据。

能否把medicalQA的数据集示例也放出来呢？

光靠看那py和sh代码要反推出来，还是有难度。

谢谢！

**Comment by Zimix0** [comment]
你好，稍后会在hugging face给出数据样例。请稍等

**Comment by JQZhai** [comment]
现在是2023年4月13日，依然没有给数据样例，根本finetune不了啊

**Comment by Zimix0** [comment]
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/93325445/231658839-f07d2f53-e4fe-4a1b-871c-8c3dbd4849df.png">
在github的readme里面是有说明数据格式的。和你理解的一样，是基于闻仲做的qa任务，所以如果是做继续训练或者非qa的训练，其实对数据稍作修改即可。qa的真实数据是这样的(jsonline)：
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/93325445/231659361-3a02681a-c220-4e3c-9f94-da60938268dd.png">
可以可参考这个分支做预训练。

**Comment by JQZhai** [comment]
模型使用说明里有且只有wenzhongqa给了数据样例，能说清楚点吗？稍作修改的修改是什么，我是个小白。

**Comment by Zimix0** [comment]
本脚本是qa任务的finetune，jsonline文件里面有2个key，question和answer。如果是对普通问本的微调，对下面文件作修改即可
修改这个文件https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/93759530769dc028f5bddfb6ca2c3f991fac0365/fengshen/data/task_dataloader/medicalQADataset.py#L56
<img width="948" alt="image" src="https://user-images.githubusercontent.com/93325445/231934248-bafb0163-ec51-440c-ae4e-0e9c6af836ac.png">
https://huggingface.co/datasets/IDEA-CCNL/PretrainCorpusDemo
