### ISSUE TITLE
微调出现 keyword arguments  {"images":[tensor]} not recognized 

### ISSUE THREAD

**Issue by Pe4nutZz** [IDEA-CCNL/Fengshenbang-LM#317]
请问有人知道是什么问题吗，是不是我哪里设置的不对

**Comment by Hzj199** [comment]
应该是在`site-packages\transformers\tokenization_utils.py` 中`PreTrainedTokenizer`的方法`def tokenize(self, text: TextInput, **kwargs) -> List[str]:`中出现的，Collator中self.tokenizer不需要输入images
