### ISSUE TITLE
闻仲finetune的方法

### ISSUE THREAD

**Issue by zhangxliang** [IDEA-CCNL/Fengshenbang-LM#32]
是否有办法在5*3090的机器上对闻仲进行finetune

**Comment by GGGGGGXY** [comment]
hello您好，很高兴收到您提交的issue，我提交了一个闻仲的finetune，可以在a100单卡上进行finetune，您可以尝试修改后在3090上试试，我们正在致力于为用户提供小资源finetune大模型的解决方案，目前还在推进中，欢迎尝试并期待您宝贵的意见 嘿嘿

https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/dev/gaoxinyu/fengshen/README.md

**Comment by zhangxliang** [comment]
由于我没用过pytorch lighting，所以只考虑了你提到的deepspeed zero stage3方案，不用修改模型也基本能完成finetune
