### ISSUE TITLE
Randeng-T5-784M-MultiTask-Chinese 用了哪个词表进行预训练的

### ISSUE THREAD

**Issue by wjy3326** [IDEA-CCNL/Fengshenbang-LM#320]
Randeng-T5-784M-MultiTask-Chinese 用了哪个词表进行预训练和微调呢，为什么我用这个模型微调出来，不会生成中文的双引号，是不是词表中没有双引号呢，能否分享下词表文件呢

**Comment by ganzhiruyi** [comment]
huggingface模型内有词表文件https://huggingface.co/IDEA-CCNL/Randeng-T5-784M-MultiTask-Chinese/blob/main/spiece.model，可以自己用sentencepiece模块加载
