### ISSUE TITLE
请问如何修改输入模型的最大长度呢

### ISSUE THREAD

**Issue by ykallan** [IDEA-CCNL/Fengshenbang-LM#321]
目前使用的预训练模型，以及引入的pipeline为：

```python
import argparse

from fengshen.models.ubert import UbertPipelines

total_parser = argparse.ArgumentParser("抽取任务")
total_parser.add_argument("--pretrained_model_path", default="Erlangshen-Ubert-330M-Chinese")
total_parser = UbertPipelines.pipelines_args(total_parser)
args = total_parser.parse_args()
```
如果输入的预测文本过长，则会报错：
```text
Traceback (most recent call last):
  File "E:/PythonMyCode/nlp_about/erlangshen_info_extract/main.py", line 33, in <module>
    result = model.predict(test_data, cuda=False)
  File "C:\ProgramData\Anaconda3\envs\fastapi\lib\site-packages\fengshen-0.0.1-py3.8.egg\fengshen\models\ubert\modeling_ubert.py", line 754, in predict
    batch_result = self.em.extract(
  File "C:\ProgramData\Anaconda3\envs\fastapi\lib\site-packages\fengshen-0.0.1-py3.8.egg\fengshen\models\ubert\modeling_ubert.py", line 650, in extract
    entity_idx_type_list = self.extract_index(
  File "C:\ProgramData\Anaconda3\envs\fastapi\lib\site-packages\fengshen-0.0.1-py3.8.egg\fengshen\models\ubert\modeling_ubert.py", line 508, in extract_index
    if span_logits[i, j] > split_value:
IndexError: index 128 is out of bounds for axis 1 with size 128
```

请问应该如何修改最大长度，或者是规避这种错误呢

**Comment by ykallan** [comment]
目前我这边的一个解决方案是，修改项目源码：
文件：`fengshen/models/ubert/modeling_ubert.py`
行数 202
修改为：
```python
class UbertDataModel(pl.LightningDataModule):
    @staticmethod
    def add_data_specific_args(parent_args):
        parser = parent_args.add_argument_group('TASK NAME DataModel')
        parser.add_argument('--num_workers', default=8, type=int)
        parser.add_argument('--batchsize', default=8, type=int)
        parser.add_argument('--max_length', default=512, type=int)
        return parent_args
```

这样可以实现修改长度，不知道后期能否进行优化，无需修改源码即可通过 argparse 进行修改

**Comment by cndebuger** [comment]
> 目前我这边的一个解决方案是，修改项目源码： 文件：`fengshen/models/ubert/modeling_ubert.py` 行数 202 修改为：
> 
> ```python
> class UbertDataModel(pl.LightningDataModule):
>     @staticmethod
>     def add_data_specific_args(parent_args):
>         parser = parent_args.add_argument_group('TASK NAME DataModel')
>         parser.add_argument('--num_workers', default=8, type=int)
>         parser.add_argument('--batchsize', default=8, type=int)
>         parser.add_argument('--max_length', default=512, type=int)
>         return parent_args
> ```
> 
> 这样可以实现修改长度，不知道后期能否进行优化，无需修改源码即可通过 argparse 进行修改
当我把max_length设置为4096时，提示：
RuntimeError: The size of tensor a (4096) must match the size of tensor b (512) at non-singleton dimension 1

请问大佬怎么解决啊~

**Comment by suolyer** [comment]
这个bug已修复，推荐使用我们最新发表在ACL2023提出的UniEX模型，https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/dev_yangping/fengshen/examples/uniex

**Comment by ykallan** [comment]
> 这个bug已修复，推荐使用我们最新发表在ACL2023提出的UniEX模型，https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/dev_yangping/fengshen/examples/uniex

请问这个UniEX模型 预计什么时候合并到主分支呢？

**Comment by suolyer** [comment]
已合并到主分支
