### ISSUE TITLE
请问Taiyi-Chinese的license是什么

### ISSUE THREAD

**Issue by HaneTooru** [IDEA-CCNL/Fengshenbang-LM#322]
请问[太乙中文模型](https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1)的license是什么？是直接沿用stable-diffusion的license么？https://huggingface.co/spaces/CompVis/stable-diffusion-license

**Comment by ganzhiruyi** [comment]
是的，因为是基于他继续训练的。
