### ISSUE TITLE
ubert模型在cpu上推理出现的问题

### ISSUE THREAD

**Issue by xjDUAN184** [IDEA-CCNL/Fengshenbang-LM#333]
大佬，我想请教一下，如果我用Ubert模型在gpu机器上训练出一个模型，但是我现在想试验一下这个模型仅使用cpu进行推理时的效率（在GPU的机器上），我应该怎么设置呢？
我尝试过将args.gpus = 0，但是在推理的时候还是使用的gpu。

**Comment by suolyer** [comment]
model.predict(,cuda=False)就可以，ubert效率比较低下，关系抽取效果也不好，可以看看我们团队最新中稿ACL2023的论文UniEX：https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/dev%2Fyangping/fengshen/examples/uniex/README.md
论文正在修改传arxiv的路上，代码和权重都开源了
