### ISSUE TITLE
没有找到关系抽取的示例呀

### ISSUE THREAD

**Issue by houpanpan** [IDEA-CCNL/Fengshenbang-LM#334]
在https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/hf-ds/fengshen/examples/ubert这文件中，并没有找到关系抽取的示例啊，可以补充下嘛，谢谢

**Comment by suolyer** [comment]
ubert关系抽取效果不是很好，可以看看我们团队最新中稿ACL2023的论文UniEX：https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/dev%2Fyangping/fengshen/examples/uniex/README.md
论文正在修改传arxiv的路上，代码和权重都开源了
