### ISSUE TITLE
Ziya-LLaMA-13B-v1会放出只经过预训练的权重吗？

### ISSUE THREAD

**Issue by drxmy** [IDEA-CCNL/Fengshenbang-LM#341]
感谢开源！

**Comment by ganzhiruyi** [comment]
目前先放出最终模型给社区使用，如果有需要我们也会放出继续训练和指令微调两阶段的模型。

**Comment by drxmy** [comment]
> 目前先放出最终模型给社区使用，如果有需要我们也会放出继续训练和指令微调两阶段的模型。

期待给出预训练权重，谢谢

**Comment by znsoftm** [comment]
在HF上已经有预训练后的基础模型了。
