### ISSUE TITLE
关于显存问题

### ISSUE THREAD

**Issue by 12xiaoni** [IDEA-CCNL/Fengshenbang-LM#342]
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/87464024/8cf3e733-e26a-42ae-9bbe-e5a1fd6df554)
请问运行这个代码需要多少显存

**Comment by sanfuyee** [comment]
@12xiaoni 
#model = LlamaForCausalLM.from_pretrained(model_path, device_map="auto") #fp32
#model = LlamaForCausalLM.from_pretrained(model_path, device_map="auto", torch_dtype=torch.half) # fp16  ---> 29G
model = LlamaForCausalLM.from_pretrained(model_path, device_map="auto", load_in_8bit=True) # int8  ---> 17G

**Comment by Liuhan703** [comment]
13b模型全精度load需要差不多52G显存，半精度则需要26G显存。

**Comment by 12xiaoni** [comment]
好的，感谢



---- 回复的原邮件 ----
| 发件人 | Liu ***@***.***> |
| 日期 | 2023年05月19日 11:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [IDEA-CCNL/Fengshenbang-LM] 关于显存问题 (Issue #342) |

13b模型全精度load需要差不多52G显存，半精度则需要26G显存。
