### ISSUE TITLE
A100单卡40G显存，报错超出显存，请看一下

### ISSUE THREAD

**Issue by CaptainQiu** [IDEA-CCNL/Fengshenbang-LM#344]
from transformers import AutoTokenizer
from transformers import LlamaForCausalLM
import torch

device = torch.device("cuda")

query="帮我写一份去西安的旅游计划"
model = LlamaForCausalLM.from_pretrained('data/Ziya-LLaMA-13B-v1', device_map="auto")
tokenizer = AutoTokenizer.from_pretrained('data/Ziya-LLaMA-13B-v1')
inputs = '<human>:' + query.strip() + '\n<bot>:'
      
input_ids = tokenizer(inputs, return_tensors="pt").input_ids.to(device)
generate_ids = model.generate(
            input_ids,
            max_new_tokens=1024, 
            do_sample = True, 
            top_p = 0.85, 
            temperature = 1.0, 
            repetition_penalty=1., 
            eos_token_id=2, 
            bos_token_id=1, 
            pad_token_id=0)
output = tokenizer.batch_decode(generate_ids)[0]
print(output)

**Comment by sanfuyee** [comment]
@CaptainQiu 
model = LlamaForCausalLM.from_pretrained(model_path, device_map="auto", torch_dtype=torch.half)

**Comment by Liuhan703** [comment]
你好！demo的代码默认是fp32加载的。你可以参考楼上用半精度加载。

**Comment by CaptainQiu** [comment]
感谢楼上两位回复，按照 @sanfuyee 的回复解决
