### ISSUE TITLE
使用example/finetune_taiyi_stable_diffusion训练的模型只能输出马赛克

### ISSUE THREAD

**Issue by zhangdiwaa** [IDEA-CCNL/Fengshenbang-LM#346]
**简介**
2023年5月19日
参考官方文档本地安装封神榜框架：https://github.com/IDEA-CCNL/Fengshenbang-LM#%E5%AE%89%E8%A3%85
然后运行 Fenshenbang-LM/fenshen/examples/finetune_taiyi_stable_diffusion/finetune.sh
训练的模型最后只能输出马赛克

**finetune硬件环境：**
市面常见的8卡3090服务器，内存314GB
实际训练的时候只调用了其中一个3090显卡，显存24GB

**finetune软件环境：**
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/2345070/4713e5f1-fe81-4d61-8785-42dc5277dffc)
其中重点：
- OS：                                         Ubuntu 18.04.4 LTS
- GCC version                              7.5.8
- python version                          3.10.11
- cuda runtaime version               9.1.85
- [conda] pytorch-lightning         1.9.5  (原始的setup文档会安装2.0以上版本导致出错，遂限定版本<2)                 
- [conda] torch                             2.0.0                   
- [conda] torchmetrics                 0.11.4                 
- [conda] torchvision                   0.15.2 

**finetune配置**
基本是按照原始的finetune.sh文件运行，注释了使用deepspeed的部分，使用fp16的方式训练。finetune.py等其他example里的文件完全没有更改。

```
#!/bin/bash
#SBATCH --job-name=finetune_taiyi # create a short name for your job
#SBATCH --nodes=1 # node count
#SBATCH --ntasks-per-node=8 # number of tasks to run per node
#SBATCH --cpus-per-task=30 # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --gres=gpu:8 # number of gpus per node
#SBATCH -o %x-%j.log # output and error log file names (%x for job id)
#SBATCH -x dgx050

# pwd=Fengshenbang-LM/fengshen/examples/pretrain_erlangshen
ROOT_DIR=../../workspace
export TORCH_EXTENSIONS_DIR=${ROOT_DIR}/torch_extendsions

MODEL_NAME=taiyi-stablediffusion-1B
MODEL_ROOT_DIR=$ROOT_DIR/${MODEL_NAME}
if [ ! -d ${MODEL_ROOT_DIR} ];then
  mkdir ${MODEL_ROOT_DIR}
fi

NNODES=1
GPUS_PER_NODE=1

MICRO_BATCH_SIZE=1

# 注释了deepspeed
# # 如果你不用Deepspeed的话 下面的一段话都可以删掉 Begin
# CONFIG_JSON="$MODEL_ROOT_DIR/${MODEL_NAME}.ds_config.json"
# ZERO_STAGE=1
# # Deepspeed figures out GAS dynamically from dynamic GBS via set_train_batch_size()
# cat <<EOT > $CONFIG_JSON
# {
#     "zero_optimization": {
#         "stage": ${ZERO_STAGE}
#     },
#     "bf16": {
#         "enabled": true
#     },
#     "train_micro_batch_size_per_gpu": $MICRO_BATCH_SIZE
# }
# EOT
# export PL_DEEPSPEED_CONFIG_PATH=$CONFIG_JSON
# ### End

DATA_ARGS="\
        --dataloader_workers 2 \
        --train_batchsize $MICRO_BATCH_SIZE  \
        --val_batchsize $MICRO_BATCH_SIZE \
        --test_batchsize $MICRO_BATCH_SIZE  \
        --datasets_path ./demo_dataset \
        --datasets_type txt \
        --resolution 512 \
        "

# 修改了model_path, 改为绝对路径（网络不好，使用git clone下载模型更快）
MODEL_ARGS="\
        --model_path /home/zhangdi/Fengshenbang-LM/fengshen/workspace/Taiyi-Stable-Diffusion-1B-Chinese-v0.1 \
        --learning_rate 1e-4 \
        --weight_decay 1e-1 \
        --warmup_ratio 0.01 \
        "

MODEL_CHECKPOINT_ARGS="\
        --save_last \
        --save_ckpt_path ${MODEL_ROOT_DIR}/ckpt \
        --load_ckpt_path ${MODEL_ROOT_DIR}/ckpt/last.ckpt \
        "
        
TRAINER_ARGS="\
        --max_epoch 10 \
        --gpus $GPUS_PER_NODE \
        --num_nodes $NNODES \
        --log_every_n_steps 100 \
        --precision bf16 \
        --default_root_dir ${MODEL_ROOT_DIR} \
        --replace_sampler_ddp False \
        --num_sanity_val_steps 0 \
        --limit_val_batches 0 \
        "
# 这是为了注释deepspeed_stage_
# TRAINER_ARGS="\
#         --max_epoch 10 \
#         --gpus $GPUS_PER_NODE \
#         --num_nodes $NNODES \
#         --strategy deepspeed_stage_${ZERO_STAGE} \
#         --log_every_n_steps 100 \
#         --precision bf16 \
#         --default_root_dir ${MODEL_ROOT_DIR} \
#         --replace_sampler_ddp False \
#         --num_sanity_val_steps 0 \
#         --limit_val_batches 0 \
#         "
# num_sanity_val_steps， limit_val_batches 通过这俩参数把validation关了

export options=" \
        $DATA_ARGS \
        $MODEL_ARGS \
        $MODEL_CHECKPOINT_ARGS \
        $TRAINER_ARGS \
        "

python3 finetune.py $options
#srun -N $NNODES --gres=gpu:$GPUS_PER_NODE --ntasks-per-node=$GPUS_PER_NODE --cpus-per-task=20 python3 pretrain_deberta.py $options
```

之后训练过程一切正常，使用example里默认的示例数据（6个图文对）总共进行10轮训练，耗时不到半个小时。

![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/2345070/f9f1a1f8-5d02-4dd4-ab99-4c9c4ca50910)

但是使用太乙的webui生成图时，不管什么prompt、什么参数都只会产生马赛克图

![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/2345070/f3fc8164-96a1-4bbf-9ce5-47999a0503d2)

请问具体是什么原因？ （本人是初次接触SD模型的finetune）

**Comment by wanng-ide** [comment]
您好，我怀疑你这个问题是因为只使用了example里面的6张图进行训练。数量太少了，导致Finetune过度，直接过拟合了。我建议您使用超过100张图之后，把LR也下降一些，再进行ft。因为finetune的数量级我们一般是建议上万的。
少量数据的情况（小于1000个图文对）我建议使用lora进行ft。

**Comment by zhangdiwaa** [comment]
> 您好，我怀疑你这个问题是因为只使用了example里面的6张图进行训练。数量太少了，导致Finetune过度，直接过拟合了。我建议您使用超过100张图之后，把LR也下降一些，再进行ft。因为finetune的数量级我们一般是建议上万的。 少量数据的情况（小于1000个图文对）我建议使用lora进行ft。
------------------------------------------------------------------------------------------------------------------------
感谢你的回复！

我们的实际训练情况：

- 不训练时，load模型可用。
- 我自己使用单张3090，用example/finetune里默认的数据（默认6个图文对），训练时间不到30分钟，训练结果是马赛克。
- 我自己使用单张3090，使用我们的国画标注数据（27000个图文对），训练时间26小时，训练结果是马赛克。
- 我的学生使用autoDL租用的3090服务器，用example/finetune里默认的数据（6个图文对），训练结果是马赛克。
- 我的学生使用autoDL租用的3090服务器，使用我们的国画标注数据（27000个图文对），训练结果是马赛克。
- 我的学生使用autoDL租用的3090服务器，使用example中的dreambooth例子（默认4张鸭子图），训练结果是马赛克。

综上，我估计可能是finetune示例里配置信息有问题，导致所有的finetune工作都有问题。所以我想了有两种可能性：

1. 比如有什么组件更新了导致不可用？在安装fengshengbang框架的过程中，就发生了这种情况，pytorch-lightning的配置要求写的是>=1.5.10, 但直接运行的话会安装2.0以上版本导致错误，所以我们更改了setup.py文件改为 'pytorch_lightning >= 1.5.10,<2'，最后安装了pytorch_lightning  1.9.5版本成功运行。现在看起来，是不是把所有的install_requires的“>=”都改成“=”安装会更好？
2. 我们的finetune脚本基本上都没有修改（只是去掉了deepspeed），是否修改其中某些配置参数会好一些呢？

还请不吝赐教。

**Comment by wxj630** [comment]
我估计可能跟你使用的stable-diffusion-webui版本有关，我建议你使用最新版的stable-diffusion-webui，然后根据https://github.com/IDEA-CCNL/stable-diffusion-webui-taiyi-scripts进行修改下适配太乙模型

**Comment by zhangdiwaa** [comment]
> 我估计可能跟你使用的stable-diffusion-webui版本有关，我建议你使用最新版的stable-diffusion-webui，然后根据[https://github.com/IDEA-CCNL/stable-diffusion-webui-taiyi-scripts进行修改下适配太乙模型](https://github.com/IDEA-CCNL/stable-diffusion-webui-taiyi-scripts%E8%BF%9B%E8%A1%8C%E4%BF%AE%E6%94%B9%E4%B8%8B%E9%80%82%E9%85%8D%E5%A4%AA%E4%B9%99%E6%A8%A1%E5%9E%8B)

感谢你，确实是你说的这样。

后面我们又试了各种方法，确定是太乙的webui有问题，而不是finetune的问题。

现在webui整起来真的复杂又麻烦，还是docker版本安装起来比较简单。我们现在主要采用下面这种直接使用命令行让太乙出图的测试方式了。

```
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1").to("cuda")

prompt = '飞流直下三千尺，油画'
image = pipe(prompt, guidance_scale=7.5).images[0]  
image.save("飞流.png")
```

**Comment by lxmmeng** [comment]
> > 我估计可能跟你使用的stable-diffusion-webui版本有关，我建议你使用最新版的stable-diffusion-webui，然后根据[https://github.com/IDEA-CCNL/stable-diffusion-webui-taiyi-scripts进行修改下适配太乙模型](https://github.com/IDEA-CCNL/stable-diffusion-webui-taiyi-scripts%E8%BF%9B%E8%A1%8C%E4%BF%AE%E6%94%B9%E4%B8%8B%E9%80%82%E9%85%8D%E5%A4%AA%E4%B9%99%E6%A8%A1%E5%9E%8B)
> 
> 感谢你，确实是你说的这样。
> 
> 后面我们又试了各种方法，确定是太乙的webui有问题，而不是finetune的问题。
> 
> 现在webui整起来真的复杂又麻烦，还是docker版本安装起来比较简单。我们现在主要采用下面这种直接使用命令行让太乙出图的测试方式了。
> 
> ```
> from diffusers import StableDiffusionPipeline
> 
> pipe = StableDiffusionPipeline.from_pretrained("IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1").to("cuda")
> 
> prompt = '飞流直下三千尺，油画'
> image = pipe(prompt, guidance_scale=7.5).images[0]  
> image.save("飞流.png")
> ```

请问您采用的这种命令行方式是基于哪个代码？是来自StableDiffusion源码吗？
