### ISSUE TITLE
能否把用到的开源数据集在readme列出一下？

### ISSUE THREAD

**Issue by lucasjinreal** [IDEA-CCNL/Fengshenbang-LM#348]
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/21303438/f48cf541-804d-42f2-adb2-363326ec0e26)

这里面提到有 许多开源数据都未看到出处。

**Comment by oswen** [comment]
Code和推理相关的数据集来源比较杂，很大一部分是我们内部构造/校验的数据，这部分不方便公开。
平行语料数据中古文翻译是直接调用ChatGPT生成的，中英互译语料来自于[维基百科json版(wiki2019zh)](https://github.com/brightmart/nlp_chinese_corpus#5%E7%BF%BB%E8%AF%91%E8%AF%AD%E6%96%99translation2019zh520%E4%B8%87%E4%B8%AA%E4%B8%AD%E8%8B%B1%E6%96%87%E5%8F%A5%E5%AD%90%E5%AF%B9)
多轮对话语料有一部分是内部构造的任务型多轮对话，其余主要来自[multiturn_chat_0.8M](https://huggingface.co/datasets/BelleGroup/multiturn_chat_0.8M)
