### ISSUE TITLE
UniEX

### ISSUE THREAD

**Issue by VolantBoy** [IDEA-CCNL/Fengshenbang-LM#349]
有幸拜读了你们在统一信息抽取上的工作《UniEX: An Effective and Efficient Framework for Unified Information Extraction via a Span-extractive Perspective》，非常棒的工作！！！我看README上说用了baike构建的弱监督数据做了预训练，然后在多项下游IE任务数据上做了微调，这里我有一些细节想确认下
1. 论文里的结果应该将UniEX模型直接在具体某一种IE任务（如实体识别）上做微调，并没有做预训练，是吗？
2. README提到的微调过程，是将所有的IE任务数据混合到一起做微调的吗？
3. 如果1是没有做预训练的结果，那做了预训练的UniEX，在下游任务上的效果你们评测过吗？

**Comment by suolyer** [comment]
hi，感谢关注
1、论文table1的结果是直接finetuning的，table2和table3的few-shot的数据集本身就划分好一部分数据用来做预训练，你可以细看参考的数据集论文。
2、是的，我们混合所有任务同时训练。
3、英文的没有合适的数据集用来做预训练。我们也主要关注中文场景，所有收集的数据集都是中文的。不过我有跑过所有任务同时训练，然后在单个数据集上继续微调，对于数据量比较小的数据集提升非常明显。另外，中文场景下，经过预训练的模型在few-shot场景下，提升也是十分明显。你也可以用我们开源的中文模型测试一下

**Comment by VolantBoy** [comment]
十分感谢回复~
请问基于baike的弱监督预训练数据是否会开源呢，以及用于微调的IE任务数据是否会开源或者列举出具体的数据集？

**Comment by suolyer** [comment]
数据开源会有一定的风险，所以这边我们暂时还没有开源的计划。微调的IE任务主要有，cluener、CMeEE、MSRA、Ontonote4、resume、weibo、DuEE、DuIE、CMeIE、WSC等，还有一些自己内部自建的以及一些比赛上收集的数据
