### ISSUE TITLE
是否会开放Ziya-LLaMA-13B-v1中预训练阶段模型？

### ISSUE THREAD

**Issue by ruidongtd** [IDEA-CCNL/Fengshenbang-LM#353]
后续是否考虑把在LLaMA-13B上继续中英数据预训练获得的模型开放出来？

**Comment by Desein-Yang** [comment]
感谢关注！目前已经开源了第一阶段预训练后的模型，模型链接：https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-13B-Pretrain-v1
