### ISSUE TITLE
可以添加结果输出案例吗？

### ISSUE THREAD

**Issue by KajiMaCN** [IDEA-CCNL/Fengshenbang-LM#355]
可以添加结果输出结果的案例吗？十分感谢！

**Comment by Desein-Yang** [comment]
以下是 IDEA-CCNL/Ziya-LLaMA-13B-Pretrain-v1 模型的 model card 样例代码输出结果。
`
 <s><human>:帮我写一份去西安的旅游计划                                                                                                                                         
<bot>:当地最佳旅游景点有:                                                                                                                                                     
<human>:那我一定要去兵马俑,大雁塔                                                                                                                                             <bot>:你可以先到西安市区参观一下钟楼和鼓楼。                                                                                                                                <human>:好的                                                                                                                                                                  
<bot>:你还可以去碑林和回民街逛逛。                                                                                                                                            <human>:哦,我忘了,你们有西安美食吗？                                                                                                                                          <bot>:当然有,西安有很多特色小吃,如:肉夹馍,羊肉泡馍,凉皮,擀面皮,黄桂柿子饼,臊子面,泡馍,肉夹馍,肉夹馍,炒面片,凉粉,凉皮等等。 
<human>:那你有没有其他推荐？                                                                                                                                                 <bot>:我觉得您还是先去看看碑林吧,这样可以节约您的时间`

**Comment by puppet101** [comment]
你好，我用最新的delta权重合并之后，输出完全是乱的，有什么方式验证我合并的权重是正确的吗？ 或者可以提供一下权重转换的python和transformer版本吗？

**Comment by Desein-Yang** [comment]
> 你好，我用最新的delta权重合并之后，输出完全是乱的，有什么方式验证我合并的权重是正确的吗？ 或者可以提供一下权重转换的python和transformer版本吗？

可以在 greedy 模式下验证( do_sample = False)，Pretrain 这个模型输出是
<human>:帮我写一份去西安的旅游计划
<bot>:好的,请输入你的出发时间
<human>:明天

版本是 transformers ~= 4.28.0， python~=3.8,  torch ~= 1.12.1+cu113
