### ISSUE TITLE
unimc环境装好运行example报错

### ISSUE THREAD

**Issue by ChaohuaZhang** [IDEA-CCNL/Fengshenbang-LM#359]
args.train = 'train'

pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler `LambdaLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if you are using a custom LR scheduler.

 args.train = 'predict'

AttributeError: 'UniMCPipelines' object has no attribute '_num_workers'

**Comment by suolyer** [comment]
可能是pytorch-lightning版本的问题，我本地测试的是1.6。

**Comment by suolyer** [comment]
可以把你完整的运行代码和报错都贴出来

**Comment by zizhec** [comment]
这句报错来自：pytorch_lightning(1.6.3版本) 的optimizer:
        if not isinstance(scheduler, LRSchedulerTypeTuple) and not is_overridden("lr_scheduler_step", model):
            raise MisconfigurationException(
                f"The provided lr scheduler `{scheduler.__class__.__name__}` doesn't follow PyTorch's LRScheduler"
                " API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if"
                " you are using a custom LR scheduler."
            )
允许的LRSchedulerTypeTuple 只包括：(torch.optim.lr_scheduler._LRScheduler, torch.optim.lr_scheduler.ReduceLROnPlateau)

但是这个scheduler 是大多模型文件里面写死的:
        scheduler = get_linear_schedule_with_warmup(
            optimizer, int(self.total_step * self.args.warmup),
            self.total_step)

可能不同的pytorch_lightning 版本可以解决，requirements 里面写的是>=1.6.3， 但1.6.3是有这个问题的。
或者直接改模型代码。

**Comment by indiejoseph** [comment]
已试多个版本，但都是相同报错，请问如何修改模型代码？
