### ISSUE TITLE
请问用子牙模型进行finetuning，数据集的格式是什么（包含多轮对话）？

### ISSUE THREAD

**Issue by jeave** [IDEA-CCNL/Fengshenbang-LM#360]
期待回复

**Comment by David-Lee-1990** [comment]
有没有微调代码？

**Comment by schwgHao** [comment]
<human>:{ROUND_1_QUERY}\n<bot>:{ROUND_1_RESPONSE}\n<human>:{ROUND_2_QUERY}\n<bot>:{ROUND_2_RESPONSE}...
这样的格式
