### ISSUE TITLE
Hugging Face model Ziya-LLaMA-13B-Pretrain-v1 can not be downloaded

### ISSUE THREAD

**Issue by sohowj** [IDEA-CCNL/Fengshenbang-LM#361]
Some of the files got an error:
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>RXZ8X4DP9CC8MK3N</RequestId><HostId>sWvMy3Lt+QFwiFjc0bZzDri9MB0NgJZ9dQ52Ra9H+A6ldd1nbAG66pAIxUK1FtFN5jjJLLI/MZc=</HostId></Error>`

**Comment by Desein-Yang** [comment]
Hi, we have checked and updated the repo IDEA-CCNL/Ziya-LLaMA-13B-Pretrain-v1. Please try again.

We found that there is an issue with the link to the model file in the repository. Thank you for your understanding.
