### ISSUE TITLE
Ziya-LLaMA-13B-Pretrain-v1的输出好像有点奇怪？

### ISSUE THREAD

**Issue by chenxichen95** [IDEA-CCNL/Fengshenbang-LM#363]
我使用的模型权重是 https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-13B-Pretrain-v1
不知道是不是上传错了权重文件？

<img width="1188" alt="Snipaste_2023-06-05_14-41-07" src="https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/32231230/1bdaafbb-d903-4b59-8351-0a2b54144076">
<img width="828" alt="Snipaste_2023-06-05_14-41-31" src="https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/32231230/9bde6946-48e2-40cd-a077-f766f6500991">

**Comment by ganzhiruyi** [comment]
因为llama的协议，这个开放的是delta权重，参考modelcards里的示例合并下原始的llama权重。

**Comment by chenxichen95** [comment]
明白了，之前下 IDEA-CCNL/Ziya-LLaMA-13B-v1 还不需要。这次没注意看~ 谢谢
