### ISSUE TITLE
ziya的vocab size从model打印出来的和从tokenzier打印出来的大小不一样，这个size不应该一样吗？

### ISSUE THREAD

**Issue by edisonzf2020** [IDEA-CCNL/Fengshenbang-LM#364]

**Comment by ganzhiruyi** [comment]
可以贴下你的代码和运行结果。

**Comment by BowieHsu** [comment]
<img width="1906" alt="截屏2023-06-07 下午3 02 50" src="https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/4092342/5020ea29-2a0f-4c34-afe7-4a665e38ccb8">
读取tokenizer的词表数是39408，模型的config.json里写的词表数是39424，是有什么没搞对吗

**Comment by desperadoola** [comment]
猜测

模型的 embedding size 为 39424 一方面为了是 64 的倍数, 另一方面 embedding size > 词表大小, 后续比较方便添加特殊 token。

**Comment by schwgHao** [comment]
> 猜测
> 
> 模型的 embedding size 为 39424 一方面为了是 64 的倍数, 另一方面 embedding size > 词表大小, 后续比较方便添加特殊 token。

没错，39424是为了方便模型并行时做tensor切分（确保被8或者16整除）而增加的，实际上不会训练39409～39424之间的token。

**Comment by BowieHsu** [comment]
@desperadoola @schwgHao 了解了，学习到了，蛮精髓的操作
