### ISSUE TITLE
请问用Ziya-LLaMA-13B-v1进行推理时，输出中夹带英文，如何解决？

### ISSUE THREAD

**Issue by ysyfrank** [IDEA-CCNL/Fengshenbang-LM#367]
使用的是https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-13B-v1 里提供的推理代码。

> Input：阅读下面的材料，根据要求写作。人们因技术发展得以更好地掌控时间，但也有人因此成了时间的仆人。这句话引发了你怎样的联想与思考？请写一篇文章。要求：选准角度，确定立意，明确文体，自拟标题；不要套作，不得抄袭；不得泄露个人信息；不少于800字。

> Output：标题：时间的仆人：技术发展对人类的影响
尊敬的评委：
技术的飞速发展为人们提 Licencia了越来越多的便利，同时也给人类带来了许多问题。其中之一就是对时间的掌控能力。在当今社会，人们可以通过各种技术手段更好地掌控时间，比如智能手机、电子邮件、时间管理应用等。这种技术发展让人们可以更加高效地利用时间，提高了工作效率。然而，与此同时，人们也因为过度依赖技术而成为了时间的仆人。（后面省略）

> Input：按要求作答。不少于700字。舞台上，戏曲演员有登场亮相的瞬间。生活中也有许多亮相时刻: 国旗下的讲话，研学成果的汇报，新产品的发布.....每一次亮相，都受到众人关注，每一次亮相，也会有
一段故事。请以“亮相”为题目，写一篇记叙文。要求:思想健康，内容充实、合理，有细节描写;语言流畅，书写清晰。

> Output：亮相
台前，灯光璀璨，演员们身着华美的戏服，在音乐声中翩 jej 然起舞。观众们聚精会神，为他们的精彩表演而喝彩。这是一场精彩的戏曲演出，而这也是舞台上的一次亮相。
舞台上的亮相，往往是演员们长时间努力的结果。他们经过严格的训练，不断精进自己的技艺。而当他们站在舞台上，展现自己的才华时，所有的付出都得到了回报。观众们为他们的表演而喝彩，为他们的努 
力而感动。这是一种难以言喻的满足感，也是一种巨大的鼓舞。
除了舞台上的亮相，生活中也有许多亮相时刻。国旗下的讲话，研学成憔的汇报，新产品的发布......每一次亮相，都受到众人关注，每一次亮相，也会有一段故事。
比如说，国旗下 troublesome的讲话。这是一种庄严而神圣的时刻。站在国旗下，面对着所有人的目光，发表一篇精彩的讲话。这需要演讲者具备出色的语言表达能力，以及深厚的知识背景。而当 ще他们成功
地完成讲话时，所有人都为他们鼓掌喝彩。这是一种极大的荣誉，也是一种巨大的鼓舞。（后面省略）

**Comment by schwgHao** [comment]
https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-13B-v1.1
试试看v1.1怎么样，我们针对中英混杂的情况做了很多纠正。

**Comment by ysyfrank** [comment]
> https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-13B-v1.1 试试看v1.1怎么样，我们针对中英混杂的情况做了很多纠正。

谢谢回复！忘记说了用的是CPU推理的，现在换成GPU以后就没有夹带英文了。猜测可能是和cpu无法加载fp16有关。
