### ISSUE TITLE
Huggingface上面的Ziya-LLaMA-13B-Pretrain-v1 是否可以直接用？跑推理出来的是乱码

### ISSUE THREAD

**Issue by tongjizzy** [IDEA-CCNL/Fengshenbang-LM#379]
请问Huggingface上面的Ziya-LLaMA-13B-Pretrain-v1 是否可以直接用？还是需要像页面上说的进行权重转换？我这边下载下来之后，跑出来的结果是乱码。另外，为什么加载的模型显示embed_tokens的输出embeding长度是39424，但是tokenizer的长度是39410，两者是否对不上？

**Comment by Desein-Yang** [comment]
1. 不能直接使用，需要按照 readme 的 usage 部分合并 Llama 原始权重得到最终模型
2. 真实 tokenizer 为 39410，不影响使用。不一致是因为训练时框架为了并行补充 dummy token 使得  embedding 可以整除 128 ，如果 llama.cpp 等无法使用可以增加到 39424.
