### ISSUE TITLE
关于Ziya-LLaMA-13B-v1使用llama.cpp进行量化部署时，tokenizer对不齐的问题

### ISSUE THREAD

**Issue by xjDUAN184** [IDEA-CCNL/Fengshenbang-LM#389]
在使用llama.cpp进行Ziya-LLaMA-13B-v1 的推理时，第一步将模型转换为ggml格式之后，将ggml模型量化时总是出现自动关闭的问题，具体表现就是卡在load model这一步，内存占用到120G左右时就自动停了。在https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/ziya_inference/llama_cpp_quantizatin_inference.py这里提到这个问题是“tokenizer对不齐的问题”，解决方式为“在词表中添加相应个数token”，如下：
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/73686733/94df67f2-5dc1-409c-aa9b-a66587849774)

我想问下如果是这个问题的话，出错的结果是我这样吗？解决方法是在Ziya-LLaMA-13B-v1里面的tokenizer.json中加吗？具体怎么加呢？

**Comment by wyzhangyuhan** [comment]
把错误输出贴上来看看

**Comment by xjDUAN184** [comment]
@wyzhangyuhan 
大佬你好，报错如下，我是用的未量化的fp16的模型去推理的
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/73686733/72f17633-67f8-4936-927c-7a70021b171a)

**Comment by xjDUAN184** [comment]
@wyzhangyuhan   大佬，我再补充一下
我觉的问题有可能出现在将[Ziya-LLaMA-13B-v1](https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-13B-v1)这个模型转换成ggml模型这一步，我是这么做的：
1、下载Ziya-LLaMA-13B-v1的delta权重以及step 1中转换好的原始LLaMA权重，使用如下脚本转换：
python3 ../Fengshenbang-LM/fengshen/utils/apply_delta.py --base 'decapoda-research/llama-13b-hf' --target ../Fengshenbang-LM/model_weights/Ziya-LLaMA-13B-v1 --delta 'IDEA-CCNL/Ziya-LLaMA-13B-v1' --low-cpu-mem   生成结果如下：
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/73686733/7a7e65bf-f8a9-4d24-96d1-f67d127e5805)
（ggml-model-f16.bin 不算，这个是下一步的结果）
2、生成ggml模型文件
python ../llama.cpp/convert.py ../Fengshenbang-LM/model_weights/Ziya-LLaMA-13B-v1    这里我对原始convert.py脚本稍作修改，首先是正则部分，将上面图片中的pytorch_model-**.bin文件都能抽取出来（图1）；其次是check_vocab_size函数（图2），这里将“params.n_vocab != vocab.vocab_size”改成了“params.n_vocab <= vocab.vocab_size”，因为Ziya-LLaMA-13B-v1和LLama-13B的vocab大小好像是不等的，这里改一下就能跑通了，能生成ggml文件了（我感觉错误可能是这里）
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/73686733/ffd57fae-4a5d-4db1-9de9-edfadb351ff7)
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/73686733/d0721b75-4454-4590-9a7c-0a8e3b1b59da)

综上，我感觉问题应该出在ggml-model-f16.bin文件这里，如果使用llama.cpp去推理的话，是不会报错的，但是也没有结果，在load model(这里是ggml-model-fp16.bin文件的导入)内存占用飙到120G之后，程序就中断了。使用llama-cpp-python推理的话，就是上下面这个错：
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/73686733/a94c1df4-9ff1-4e29-9297-242e5454dd8d)
所以这里要怎么改呢？也就是“自行在词表中添加相应个数token”具体要怎么做呢？

**Comment by wyzhangyuhan** [comment]
是 不要改llama.cpp原始的转换代码。

对于没对齐的情况，系统可能报错如下：
```
Exception: Vocab size mismatch (model has 39424, but /Ziya-LLaMA-13B-RLHF-V1/tokenizer.model combined with /Ziya-LLaMA-13B-RLHF-V1/added_tokens.json has 39422).
```
可以修改hf格式模型里的`added_tokens.json`文件为以下:
```
{
  "<bot>": 39409,
  "<human>": 39408,
  "39410":39410,
  "39411":39411,
  "39412":39412,
  "39413":39413,
  "39414":39414,
  "39415":39415,
  "39416":39416,
  "39417":39417,
  "39418":39418,
  "39419":39419,
  "39420":39420,
  "39421":39421,
  "39422":39422,
  "39423":39423
}

```

**Comment by xjDUAN184** [comment]
@wyzhangyuhan 非常感谢大佬的帮助，修改added_tokens.json之后已经能够成功推理出结果。
但是又遇到了另外一个问题，我在使用llama_cpp_quantizatin_inference.py这个脚本进行推理，这里主要使用的是llama-cpp-python的方式，我按照下图中的命令（CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python）安装了llama-cpp-python，但是，我在推理时发现并没有使用gpu。
![image](https://github.com/IDEA-CCNL/Fengshenbang-LM/assets/73686733/333ecfd8-02e0-4847-ad92-2ff14a60cc80)
检查了下面的代码：
llm = Llama(model_path=MODEL_PATH, verbose=True, n_gpu_layers=40)
感觉没问题啊，n_gpu_layers=40也设置了。但是就是不用gpu。我想问问大佬这个问题怎么解决？
还有就是现在的推理速度大概为120ms~140ms一个token，我尝试过修改线程数和n_gpu_layers，发现推理速度不能再提高了，想请教下还有没有提升推理速度的方式？

**Comment by wyzhangyuhan** [comment]
量化或许可以快一点

**Comment by Zimix0** [comment]
> 是 不要改llama.cpp原始的转换代码。
> 
> 对于没对齐的情况，系统可能报错如下：
> 
> ```
> Exception: Vocab size mismatch (model has 39424, but /Ziya-LLaMA-13B-RLHF-V1/tokenizer.model combined with /Ziya-LLaMA-13B-RLHF-V1/added_tokens.json has 39422).
> ```
> 
> 可以修改hf格式模型里的`added_tokens.json`文件为以下:
> 
> ```
> {
>   "<bot>": 39409,
>   "<human>": 39408,
>   "39410":39410,
>   "39411":39411,
>   "39412":39412,
>   "39413":39413,
>   "39414":39414,
>   "39415":39415,
>   "39416":39416,
>   "39417":39417,
>   "39418":39418,
>   "39419":39419,
>   "39420":39420,
>   "39421":39421,
>   "39422":39422,
>   "39423":39423
> }
> ```

关于这个有一个更简单的修复方式，查看了源码，“model has 39424”中的39424是来自于模型仓库路径里面的config.json，直接读取的vocab_size，可以直接修改这个值为39410即可
