### ISSUE TITLE
很好的工作，希望开源deberta large版本的uniex模型。或者开放出uniex预训练数据

### ISSUE THREAD

**Issue by kxleee** [IDEA-CCNL/Fengshenbang-LM#391]

**Comment by suolyer** [comment]
我们近期可能不会推出uniex的其他版本，涉及到版权和安全的问题，数据我们也无法进行开源。你参考uniex的训练代码对你的数据进行finetune来满足业务需求https://github.com/IDEA-CCNL/Fengshenbang-LM/tree/main/fengshen/examples/uniex

**Comment by adalele** [comment]
你好，请问直接运行train.sh的脚本会出现  total_parser = UniEXPipelines.pipelines_args(total_parser)
AttributeError: type object 'UniEXPipelines' has no attribute 'pipelines_args'
的错误，如何修改呢
