### ISSUE TITLE
麻烦大佬提供一下ziya模型做c-eval的代码

### ISSUE THREAD

**Issue by 13269279918** [IDEA-CCNL/Fengshenbang-LM#393]
我们希望测一下微调过后的ziya模型在C-eval上的表现，用于评定模型的遗忘情况
烦请说明一下代码的使用方式，感谢

**Comment by Desein-Yang** [comment]
基于[这份代码](https://github.com/SJTU-LIT/ceval)我们支持了 ziya 的评估， 需要解压后 ziya.py 放在 evaluators 下，eval.py 替换原有 eval.py

配置到 MODEL, DATA 路径，运行 
`python eval.py --ntrain 5 --few_shot --save_name 5shot --model_name IDEA-CCNL/Ziya-LLaMA-13B--ziya_model_dir $MODEL --dataset_dir $DATA --cot --subject all --cuda_device 0`


[ziya_eval.zip](https://github.com/IDEA-CCNL/Fengshenbang-LM/files/11914862/ziya_eval.zip)
