### ISSUE TITLE
有人成功跑通uniex吗？

### ISSUE THREAD

**Issue by AnitaSherry** [IDEA-CCNL/Fengshenbang-LM#400]
1、uniex使用的pytorch_lightning版本过时了
2、使用example.py微调时，模型不使用验证集进行验证
3、代码中没有设置保存模型
4、看代码训练完成后使用test_data进行predict，错误率还很高（训练了50轮，损失从700降到0.1）
5、fengshen/pipelines/information_extraction.py中第60行和61行，摆设吗

**Comment by suolyer** [comment]
hello，把你认为不合理的改一下提个pr
