### ISSUE TITLE
Erlangshen-Roberta-110M-NLI 请问是用了哪些公开的数据集fine-tune?

### ISSUE THREAD

**Issue by chinaids** [IDEA-CCNL/Fengshenbang-LM#404]
huggingface上的描述：
模型信息 Model Information
基于[chinese-roberta-wwm-ext-base](https://huggingface.co/hfl/chinese-roberta-wwm-ext)，我们在收集的4个中文领域的NLI（自然语言推理）数据集，总计1014787个样本上微调了一个NLI版本。

请问一下能分享用的是哪几个数据集吗？

**Comment by suolyer** [comment]
哈喽，你好，我们收集的数据集有：snli，cmnli，ocnli，xnli
