### ISSUE TITLE
IDEA-CCNL/Randeng-BART-139M 微调结果不理想？

### ISSUE THREAD

**Issue by FutureWithoutEnding** [IDEA-CCNL/Fengshenbang-LM#405]
我正在微调BART用于文本摘要，考虑了两个预训练BART：
- IDEA-CCNL/Randeng-BART-139M
- fnlp/bart-base-chinese

但是不知道为什么，`IDEA-CCNL/Randeng-BART-139M`的效果，比不上`fnlp/bart-base-chinese`，在rouge-1上大约相差10个点。
这两个模型处理预训练参数以外，就是Tokenized的区别了，前一个是T5Tokenizer，后一个是BertTokenizer，这会带来这么多差距吗？还是什么其他的问题？

有没有人知道是什么原因？

**Comment by Desein-Yang** [comment]
下游任务性能和预训练语料、tokenizer 都有关。和微调方式也有关系，可能需要提供更多信息看看，比如样本构造、超参数等。

**Comment by FutureWithoutEnding** [comment]
@Desein-Yang 感谢回复。
导致结果不理想的原因已找到，是由于`IDEA-CCNL/Randeng-BART-139M`的Tokenizer将中文逗号（"，"）都转化为英文逗号所致。

另外，根据你们的微调经验，有关于微调`IDEA-CCNL/Randeng-BART-139M`的经验和超参数选择的建议吗？

**Comment by Desein-Yang** [comment]
> @Desein-Yang 感谢回复。 导致结果不理想的原因已找到，是由于`IDEA-CCNL/Randeng-BART-139M`的Tokenizer将中文逗号（"，"）都转化为英文逗号所致。
> 
> 另外，根据你们的微调经验，有关于微调`IDEA-CCNL/Randeng-BART-139M`的经验和超参数选择的建议吗？

谢谢指出！我们会尝试修复。

超参数，我们在问答任务上也做过微调，我们预训练是 1e-4，因此微调最好不要超过这个lr 否则对其他性能影响比较大，lr 1e-5 warmup 1e-4 x 总步数这个量级会比较好。可以参考我们 finetune-bart 这个下面的其他超参数。
