### ISSUE TITLE
README 很中二

### ISSUE THREAD

**Issue by tpoisonooo** [IDEA-CCNL/Fengshenbang-LM#417]
不过我喜欢！
赞。

**Comment by tpoisonooo** [comment]
“如今的基础模型，尤其是语言模型，正在被英文社区主导着。与此同时，中文作为这个世界上最大的口语语种（母语者中），却缺乏系统性的研究资源支撑，这使得中文领域的研究进展相较于英文来说有些滞后。

这个世界需要一个答案。”

嗨嗨。

**Comment by wduo** [comment]
这个issue很中二
