### ISSUE TITLE
燃灯 T5 生成模型没法使用

### ISSUE THREAD

**Issue by iseesaw** [IDEA-CCNL/Fengshenbang-LM#44]
感谢提供的中文大模型。

燃灯 T5 生成模型使用目录 `fengshen` 中的 `T5ForConditionalGeneration` ，对于 README 中例子无法正常生成

```
输入：北京是中国的<extra_id_0>
生成结果：'[PAD] <extra_id_0> [eos] <extra_id_0> 。 [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos]'
```

另外，例子代码貌似有问题，需要传入 batch 才能生成。

**Comment by suolyer** [comment]
这是因为我们主要基于 megatron 进行训练的，tokenizer 和 generate 这些都不能直接用huggingface 现成的。后续我们会基于huggingface 开源不同版本参数量的T5，也是为了方便大家使用，敬请关注哟！

**Comment by suolyer** [comment]
> 感谢提供的中文大模型。
> 
> 燃灯 T5 生成模型使用目录 `fengshen` 中的 `T5ForConditionalGeneration` ，对于 README 中例子无法正常生成
> 
> ```
> 输入：北京是中国的<extra_id_0>
> 生成结果：'[PAD] <extra_id_0> [eos] <extra_id_0> 。 [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos]'
> ```
> 
> 另外，例子代码貌似有问题，需要传入 batch 才能生成。


我们使用的是根据概率进行采样的生成策略。所以每次生成结果会有不一致的情况

**Comment by suolyer** [comment]
> 感谢提供的中文大模型。
> 
> 燃灯 T5 生成模型使用目录 `fengshen` 中的 `T5ForConditionalGeneration` ，对于 README 中例子无法正常生成
> 
> ```
> 输入：北京是中国的<extra_id_0>
> 生成结果：'[PAD] <extra_id_0> [eos] <extra_id_0> 。 [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos] [eos]'
> ```
> 
> 另外，例子代码貌似有问题，需要传入 batch 才能生成。


我们使用的是根据概率进行采样的生成策略。所以每次生成结果会有不一致的情况

**Comment by iseesaw** [comment]
抱歉，我有点不太明白您的意思。

README 里面写的是:

> 由于T5结构的燃灯-770M模型是基于Megatron进行训练的，而Megatron的T5模型结构与HuggingFace的T5模型结构有略微的区别，不能直接使用HuggingFace的T5模型进行导入。因此需要从本仓库的fengshen框架导入，需要将fengshen放在你的工程文件夹。

Issue 里又说到:

> 这是因为我们主要基于 megatron 进行训练的，tokenizer 和 generate 这些都不能直接用huggingface 现成的。后续我们会基于huggingface 开源不同版本参数量的T5，也是为了方便大家使用，敬请关注哟！

目前我按照 README 的说明使用 `fengshen` 框架的 T5 模型没办法正常生成，所以按照 Issue 里面的说法，README 写的有问题， `fengshen` 框架的 T5 模型也不支持燃灯模型的正常生成，请问是这样吗？ 谢谢回复~

**Comment by suolyer** [comment]
> 模型

不知道你是否是直接 copy 的readme的示例脚本来运行，我们重新跑了下那个示例是可以正常生成“首都”的啊，

**Comment by ganzhiruyi** [comment]
huggingface已开源基于mt5继续训练的T5版本
https://huggingface.co/IDEA-CCNL/Randeng-T5-77M
https://huggingface.co/IDEA-CCNL/Randeng-T5-784M
@iseesaw
