### ISSUE TITLE
燃灯 megatron_t5 与Huggingface t5的区别

### ISSUE THREAD

**Issue by renmada** [IDEA-CCNL/Fengshenbang-LM#49]
根据megatron_t5代码的备注，区别在于layer norm 和 几个bias=True
请问我的理解对吗

**Comment by ganzhiruyi** [comment]
是的，后续也会开源huggingface版本的t5，敬请期待！

**Comment by ganzhiruyi** [comment]
huggingface已开源基于mt5继续训练的T5版本
https://huggingface.co/IDEA-CCNL/Randeng-T5-77M
https://huggingface.co/IDEA-CCNL/Randeng-T5-784M
