### ISSUE TITLE
请问Randeng-MegatronT5-770M可以像huggingface T5有一个num_return_sequences参数来获得多个返回结果吗？

### ISSUE THREAD

**Issue by zjk000** [IDEA-CCNL/Fengshenbang-LM#50]

**Comment by suolyer** [comment]
我们也有尝试过，可以直接用huggingface的 generate，但生成的结果不佳。所以我们自己实现的一个简单的generate，想要生成多个结果可以修改这个函数。如果想直接用huggingface的generate，可以把[modeling_megatron_t5.py]的第1729行实现的generate注释掉(https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/models/megatron_t5/modeling_megatron_t5.py)
```
  def generate(self, input_ids=None, max_length=512):

        input_ids = torch.tensor(input_ids)
        if len(input_ids.shape) < 2:
            input_ids = input_ids.unsqueeze(0)
        decode_input_id = [21128]   # [BOS]的token_id为21128
        for i in range(max_length):
            tensor_decode_input_id = torch.tensor([decode_input_id])
            forword_output = self.forward(input_ids=input_ids,
                                          decoder_input_ids=tensor_decode_input_id)
            logits = forword_output.logits
            logits = torch.nn.functional.softmax(
                logits, dim=-1).cpu().detach().numpy()[0]

            last_output_id = int(np.random.choice(
                logits.shape[1], p=logits[-1]))
            if last_output_id == 21129:  # [EOS]的token_id为21129
                break
            else:
                decode_input_id.append(last_output_id)

        return decode_input_id
```

**Comment by ganzhiruyi** [comment]
huggingface已开源基于mt5继续训练的T5版本
https://huggingface.co/IDEA-CCNL/Randeng-T5-77M
https://huggingface.co/IDEA-CCNL/Randeng-T5-784M

**Comment by SIAAAAAA** [comment]
> 我们也有尝试过，可以直接用huggingface的 generate，但生成的结果不佳。所以我们自己实现的一个简单的generate，想要生成多个结果可以修改这个函数。如果想直接用huggingface的generate，可以把[modeling_megatron_t5.py]的第1729行实现的generate注释掉(https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/models/megatron_t5/modeling_megatron_t5.py)
> 
> ```
>   def generate(self, input_ids=None, max_length=512):
> 
>         input_ids = torch.tensor(input_ids)
>         if len(input_ids.shape) < 2:
>             input_ids = input_ids.unsqueeze(0)
>         decode_input_id = [21128]   # [BOS]的token_id为21128
>         for i in range(max_length):
>             tensor_decode_input_id = torch.tensor([decode_input_id])
>             forword_output = self.forward(input_ids=input_ids,
>                                           decoder_input_ids=tensor_decode_input_id)
>             logits = forword_output.logits
>             logits = torch.nn.functional.softmax(
>                 logits, dim=-1).cpu().detach().numpy()[0]
> 
>             last_output_id = int(np.random.choice(
>                 logits.shape[1], p=logits[-1]))
>             if last_output_id == 21129:  # [EOS]的token_id为21129
>                 break
>             else:
>                 decode_input_id.append(last_output_id)
> 
>         return decode_input_id
> ```

Hi！
我使用了你们实现的HF版本Megatron-T5模型，在我自己的任务上（上文生成下文) 测试了这里实现的generate() 和HF自带的generate() 在greedy search时的结果不同，偏差来源于官方的generate使用了past_key_values来避免重复的decoder内部计算。请问你们有发现类似现象吗？

下面是我在你们实现的generate()修改的贪心解：

```
    def generate(self, input_ids=None, max_length=512, do_sample=True):

        input_ids = torch.tensor(input_ids)
        if len(input_ids.shape) < 2:
            input_ids = input_ids.unsqueeze(0)
        decode_input_id = [1]   # [BOS]的token_id为1
        past_key_values = None
        for i in range(max_length):
            tensor_decode_input_id = torch.tensor([decode_input_id])
            forword_output = self.forward(input_ids=input_ids.cuda(),
                                          decoder_input_ids=tensor_decode_input_id.cuda())
            
            # check use past_key_values
            # forword_output = self.forward(input_ids=input_ids.cuda(),
            #                               past_key_values=past_key_values,
            #                               decoder_input_ids=tensor_decode_input_id[:,-1].unsqueeze(-1).cuda())
            logits = forword_output.logits
            # past_key_values = forword_output.past_key_values
            logits = torch.nn.functional.softmax(
                logits, dim=-1).cpu().detach().numpy()[0]
            if not do_sample:
                last_output_id = logits[-1].argmax()
            else:
                last_output_id = int(np.random.choice(
                logits.shape[1], p=logits[-1]))

            if last_output_id == 8002:  # [EOS]的token_id为8002
                break
            else:
                decode_input_id.append(last_output_id)
        return decode_input_id

```
