### ISSUE TITLE
Hi, there are some questions about training hardware👋

### ISSUE THREAD

**Issue by AnShengqiang** [IDEA-CCNL/Fengshenbang-LM#57]
I noticed that you wrote "32张A100训练14天" in the document. [Erlangshen-MegatronBert-1.3B.md](https://github.com/IDEA-CCNL/Fengshenbang-doc/blob/main/source/docs/%E4%BA%8C%E9%83%8E%E7%A5%9E%E7%B3%BB%E5%88%97/Erlangshen-MegatronBert-1.3B.md)

I have some questions:
1. Does 32 A100 mean (8 cards in one machine) * 4 or (32 cards in one machine) * 1? (In other words, multiple cards on one machine or multiple machines)
2. If multiple machines, how do these machines communicate at the hardware level? (NVSwitch+NVlink or netword card?)

We look forward to your answer, thank you ^_^

**Comment by ganzhiruyi** [comment]
1. (8 cards in one machine) * 4
2. NVlink between gpus in one machine, IB between machines
This model pretrained using Megatron-LM framework.

**Comment by AnShengqiang** [comment]
Thank you. That's very helpful.
