### ISSUE TITLE
Code example to finetune Erlangshen-Roberta-330M-Sentiment

### ISSUE THREAD

**Issue by harrywang** [IDEA-CCNL/Fengshenbang-LM#67]
Hi, 

Thanks a lot for sharing the pre-trained models. We are using the following model for a research project with hotel reviews in Chinese.
https://huggingface.co/IDEA-CCNL/Erlangshen-Roberta-330M-Sentiment

Many positive reviews are labeled as negative by the model such as the following one:
<img width="690" alt="Screen Shot 2022-06-18 at 4 47 31 PM" src="https://user-images.githubusercontent.com/595772/174456608-39293b8c-5c29-4fb3-bcb9-0b5412e933fa.png">

We would like to fine-tune this model after correcting the labeling results and wonder whether you can give us some pointers on how to do that.

Thanks a lot!

**Comment by suolyer** [comment]
> Hi,
> 
> Thanks a lot for sharing the pre-trained models. We are using the following model for a research project with hotel reviews in Chinese. https://huggingface.co/IDEA-CCNL/Erlangshen-Roberta-330M-Sentiment
> 
> Many positive reviews are labeled as negative by the model such as the following one: <img alt="Screen Shot 2022-06-18 at 4 47 31 PM" width="690" src="https://user-images.githubusercontent.com/595772/174456608-39293b8c-5c29-4fb3-bcb9-0b5412e933fa.png">
> 
> We would like to fine-tune this model after correcting the labeling results and wonder whether you can give us some pointers on how to do that.
> 
> Thanks a lot!

you can refer to our demo with text classification [https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/classification/finetune_classification.sh](https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/classification/finetune_classification.sh)

**Comment by haonit** [comment]
https://huggingface.co/IDEA-CCNL/Erlangshen-Roberta-330M-Sentiment 模型本身没有预训练么？为什么”干净整洁很好“这么明显的积极评价会预测为消极呢？
