### ISSUE TITLE
transformers-4.9.2似乎已有RoFormer结构相关实现？

### ISSUE THREAD

**Issue by nlp4whp** [IDEA-CCNL/Fengshenbang-LM#7]
感谢大家的一系列开源工作，我有个疑问；我这里transformers-4.9.2似乎已有RoFormer结构相关实现，是与本项目中的实现有差异么

**Comment by suolyer** [comment]
感谢关注，我们的RoFormer与HuggingFace的实现主要有几个区别：<br>1、我们是双任务（BERT任务和GPT任务）一起训练，因此内部关于attention矩阵的mask做了特殊的处理。<br>2、LayerNorm实现不同，我们的RoFormer整体结构使用的是pre-LayerNorm，而HuggingFace的实现使用的post-LayerNorm，两者的区别可见[论文](https://readpaper.com/pdf-annotate/note?noteId=625841982191538176&pdfId=4500348668766478337)。<br>3、预训练结构不同，我们预训练时去掉了针对【CLS】做的分类任务，同时 LMPredictionHead 的实现是直接复用word_embedding矩阵，没有额外添加一层线性层。

**Comment by suolyer** [comment]
> 感谢大家的一系列开源工作，我有个疑问；我这里transformers-4.9.2似乎已有RoFormer结构相关实现，是与本项目中的实现有差异么
