### ISSUE TITLE
麻烦问下太乙多模态模型提供的预训练模型只有英文版本吗IDEA-CCNL/Taiyi-Roberta-124M-D；中文版不知道有吗

### ISSUE THREAD

**Issue by lonngxiang** [IDEA-CCNL/Fengshenbang-LM#70]

**Comment by ganzhiruyi** [comment]
中文版本已经训练了一版，还在测试效果，完善example，预计1-2周内会放出来

**Comment by lonngxiang** [comment]
> 中文版本已经训练了一版，还在测试效果，完善example，预计1-2周内会放出来

期待，感谢开源，非常棒的工作

**Comment by ganzhiruyi** [comment]
> > 中文版本已经训练了一版，还在测试效果，完善example，预计1-2周内会放出来
> 
> 期待，感谢开源，非常棒的工作

中文版本的CLIP已经开源：https://huggingface.co/IDEA-CCNL/Taiyi-CLIP-Roberta-102M-Chinese

**Comment by lonngxiang** [comment]
> > > 中文版本已经训练了一版，还在测试效果，完善example，预计1-2周内会放出来
> > 
> > 
> > 期待，感谢开源，非常棒的工作
> 
> 中文版本的CLIP已经开源：https://huggingface.co/IDEA-CCNL/Taiyi-CLIP-Roberta-102M-Chinese @lonngxiang

感谢开源，这就去研究下；看图像有单独乘 logit_scale是尺度系数，这是什么原因呢，我看clip官方案例里没有用

**Comment by Weifeng-Chen** [comment]
> 

我们把clip的text encoder换成了中文pretrained过的模型，因此不能直接用 clip(image, text)，这个inference函数里面有logit_scale的实现，是为了让最后算出来的相似度拉的够开的。

**Comment by Weifeng-Chen** [comment]
> > > > 中文版本已经训练了一版，还在测试效果，完善example，预计1-2周内会放出来
> > > 
> > > 
> > > 期待，感谢开源，非常棒的工作
> > 
> > 
> > 中文版本的CLIP已经开源：https://huggingface.co/IDEA-CCNL/Taiyi-CLIP-Roberta-102M-Chinese @lonngxiang
> 
> 感谢开源，这就去研究下；看图像有单独乘 logit_scale是尺度系数，这是什么原因呢，我看clip官方案例里没有用


我们把clip的text encoder换成了中文pretrained过的模型，因此不能直接用 clip(image, text)，这个forward函数里面有logit_scale的实现，是为了让最后算出来的相似度拉的够开的。

**Comment by un-certainty** [comment]
> > > > > 中文版本已经训练了一版，还在测试效果，完善example，预计1-2周内会放出来
> > > > 
> > > > 
> > > > 期待，感谢开源，非常棒的工作
> > > 
> > > 
> > > 中文版本的CLIP已经开源：https://huggingface.co/IDEA-CCNL/Taiyi-CLIP-Roberta-102M-Chinese @lonngxiang
> > 
> > 
> > 感谢开源，这就去研究下；看图像有单独乘 logit_scale是尺度系数，这是什么原因呢，我看clip官方案例里没有用
> 
> 我们把clip的text encoder换成了中文pretrained过的模型，因此不能直接用 clip(image, text)，这个forward函数里面有logit_scale的实现，是为了让最后算出来的相似度拉的够开的。

@Weifeng-Chen 
请问我这个理解是否正确：logit_scale是与输入image无关的常量（值为4.6052，exp后是100）。logit_scale并不改变余弦值的相对大小。。

**Comment by Weifeng-Chen** [comment]
【自动恢复】来信已收到，我将尽快回复你！
