### ISSUE TITLE
Pegasus 如何使用

### ISSUE THREAD

**Issue by WangYuanZhiWang** [IDEA-CCNL/Fengshenbang-LM#78]
请问如何使用您提供的预训练好的中文Pegasus模型？
我在examples/Pegasus 里编写脚本运行，出现以下错误：

Building prefix dict from the default dictionary ...Dumping model to file cache /cognitive_comp/dongxiaoqun/software/jieba/tmp/jieba.cache
Dump cache file failed.
Traceback (most recent call last):
  File "/home/wangyx/miniconda3/envs/wang/lib/python3.8/site-packages/jieba/__init__.py", line 150, in initialize
    fd, fpath = tempfile.mkstemp(dir=tmpdir)
  File "/home/wangyx/miniconda3/envs/wang/lib/python3.8/tempfile.py", line 331, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/wangyx/miniconda3/envs/wang/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/cognitive_comp/dongxiaoqun/software/jieba/tmp/tmp7knonap8'
Loading model cost 0.631 seconds.
Prefix dict has been built successfully.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategymore precisely by providing a specific strategy to `truncation`.

**Comment by dongxqm** [comment]
hi 你好，https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/pegasus/tokenizers_pegasus.py

**Comment by dongxqm** [comment]
hi，你好，请参考这个 tokenizers_pegasus.py，修改一下jieba的默认tmp路径， https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/pegasus/tokenizers_pegasus.py

**Comment by WangYuanZhiWang** [comment]
> hi，你好，请参考这个 tokenizers_pegasus.py，修改一下jieba的默认tmp路径， https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/pegasus/tokenizers_pegasus.py `jieba.dt.tmp_dir = os.path.expanduser("/cognitive_comp/dongxiaoqun/software/jieba/tmp/")` 修改为你的路径位置

ok解决了，原来jieba新建个tmp的路径就可以
感谢您的代码以及预训练模型！
