### ISSUE TITLE
torch.distributed.launch 分布式训练longformer报错

### ISSUE THREAD

**Issue by PerfeZ** [IDEA-CCNL/Fengshenbang-LM#84]
longformer model训练报错

使用该分布式训练方式时，系统报错
入口使用方式：python -m torch.distributed.launch --nproc_per_node $NUM_GPU --master_port $PORT_ID finetune.py

错误信息：
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.

单卡训练时
入口方式python  finetune.py是正常的

请问，可能的原因是什么呢？

**Comment by ganzhiruyi** [comment]
你好，从你提供的信息来看大概率是你分布式的问题，可以参考我们fengshen框架的finetune代码，单卡和多卡切换非常方便。https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/classification/finetune_classification.sh
https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/classification/finetune_classification.py
