### ISSUE TITLE
请问 funetune Pegasus 需要的数据格式是什么样的？谢谢！

### ISSUE THREAD

**Issue by Iven-Wang** [IDEA-CCNL/Fengshenbang-LM#87]
https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/1415779fc9b1578c24981332a29d1107e0e42b8e/fengshen/examples/summary/randeng_t5_70M_summary.sh#L91

**Comment by ganzhiruyi** [comment]
这个数据集来自于LCSTS，目录下包含train.jsonl, valid.jsonl, test_public.jsonl，数据格式如下：
{"summary": "2011香港叱咤乐坛颁奖礼赢家都是实力派", "text": "由香港商业电台叱咤903举办的叱咤乐坛流行榜颁奖典礼，每年元旦如期举行，是香港的四大颁奖典礼中最好玩、最多元的一个，同时也是最支持唱作歌手的一个。本届2011叱咤颁奖礼也如往年那样，众多实力派歌手都获得了属于他们的奖项。"}
