### ISSUE TITLE
二郎神模型中遇到不同文档相似度都趋近于 0.5 的问题

### ISSUE THREAD

**Issue by T-baby** [IDEA-CCNL/Fengshenbang-LM#88]
使用的模型是：

IDEA-CCNL/Erlangshen-MegatronBert-1.3B

按照下列的流程将文本转为向量：

- encode 文本，获得向量数组。
- 对向量数组 mean pooling 合为一个。
- 对 A 和 B 文本都进行上述操作，得到的两个结果计算 cosine 值。

```python
from sentence_transformers import util
print(util.cos_sim(encode(["今天天气真好"]), encode(["天天向上"])))
```

输出：

```
tensor([[0.5146]], device='cuda:0')
```

**Comment by T-baby** [comment]
IDEA-CCNL/Erlangshen-MegatronBert-1.3B-NLI 

这个模型会更加奇怪。相似度会高达 0.85

**Comment by ganzhiruyi** [comment]
如果只是做相似度任务，可以试下IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity。如果想用来做句子表示，二郎神因为训练主要还是mlm+sop，没有句子表示的任务，所以确实分得不是很开，我试了下cls或者last_hidden_state mean pooling，cosine similarity确实都比较高。后续我们也会开源一些句子向量的预训练模型，用于句子向量表示和检索，敬请期待。
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/4384420/180910990-362af3be-a6e9-4198-9930-d3fa4767798c.png">

**Comment by T-baby** [comment]
好像没有看到 IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity 的介绍，像中文的 Bert、RoBerta 也没出现类似的情况。而且我试了周文王的模型也存在类似趋于 0.5 的问题。

**Comment by ganzhiruyi** [comment]
1. https://huggingface.co/IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity
2. 我刚用下面这份代码测试了下Erlangshen-MegatronBert-1.3B和hfl/chinese-macbert-base，Erlangshen-MegatronBert-1.3B是0.9690和0.6605，hfl/chinese-macbert-base是0.9275和0.7514，看起来也没有你说的问题。

```
import torch
from transformers import BertTokenizer, MegatronBertModel, BertModel
pretrained_path = 'IDEA-CCNL/Erlangshen-MegatronBert-1.3B'
pretrained_path = 'hfl/chinese-macbert-base'
tokenizer = BertTokenizer.from_pretrained(pretrained_path)
a = "今天天气真好"
b = "天天向上"
# model = MegatronBertModel.from_pretrained(pretrained_path)
model = BertModel.from_pretrained(pretrained_path)
inputa = tokenizer(a, return_tensors='pt')
inputb = tokenizer(b, return_tensors='pt')
# print(inputa, inputb)
ma = model(**inputa)
mb = model(**inputb)
print(torch.cosine_similarity(ma.pooler_output, mb.pooler_output))
print(torch.cosine_similarity(ma.last_hidden_state.mean(axis=1), mb.last_hidden_state.mean(axis=1)))
```

**Comment by T-baby** [comment]
我试试看你这份代码的写法。谢谢你。

**Comment by T-baby** [comment]
发现个更神奇的事情：
```python
a = "今天晚上要不去吃西餐吧？ "
b = "当预算只有十万元时，买哪种车最好？"
inputa = tokenizer(a, return_tensors='pt')
inputa.to(device)
inputb = tokenizer(b, return_tensors='pt')
inputb.to(device)
ma = model(**inputa)
mb = model(**inputb)
print(torch.cosine_similarity(ma.pooler_output, mb.pooler_output))
```
tensor([0.8589], device='cuda:0', grad_fn=<DivBackward0>)

当样本为 <十万预算买什么车好？,当预算只有十万元时，买哪种车最好？>
相似度为 0.9258

**Comment by T-baby** [comment]
IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity 结果如下：

```python
from transformers import MegatronBertConfig, MegatronBertModel
from transformers import BertTokenizer
import torch
import numpy as np
import pandas as pd

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

tokenizer = BertTokenizer.from_pretrained("IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity", cache_dir="/data/transformers_cache")
config = MegatronBertConfig.from_pretrained("IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity", cache_dir="/data/transformers_cache")
model = MegatronBertModel.from_pretrained("IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity", cache_dir="/data/transformers_cache")
model.to(device)
model.eval()

a = "今天晚上要不去吃西餐吧？ "
b = "当预算只有十万元时，买哪种车最好？"
inputa = tokenizer(a, return_tensors='pt')
inputa.to(device)
inputb = tokenizer(b, return_tensors='pt')
inputb.to(device)
ma = model(**inputa)
mb = model(**inputb)
print(torch.cosine_similarity(ma.pooler_output, mb.pooler_output))
```

输出为 tensor([0.9866], device='cuda:0', grad_fn=<DivBackward0>)

**Comment by ganzhiruyi** [comment]
> IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity 结果如下：
> 
> ```python
> from transformers import MegatronBertConfig, MegatronBertModel
> from transformers import BertTokenizer
> import torch
> import numpy as np
> import pandas as pd
> 
> device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
> 
> tokenizer = BertTokenizer.from_pretrained("IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity", cache_dir="/data/transformers_cache")
> config = MegatronBertConfig.from_pretrained("IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity", cache_dir="/data/transformers_cache")
> model = MegatronBertModel.from_pretrained("IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity", cache_dir="/data/transformers_cache")
> model.to(device)
> model.eval()
> 
> a = "今天晚上要不去吃西餐吧？ "
> b = "当预算只有十万元时，买哪种车最好？"
> inputa = tokenizer(a, return_tensors='pt')
> inputa.to(device)
> inputb = tokenizer(b, return_tensors='pt')
> inputb.to(device)
> ma = model(**inputa)
> mb = model(**inputb)
> print(torch.cosine_similarity(ma.pooler_output, mb.pooler_output))
> ```
> 
> 输出为 tensor([0.9866], device='cuda:0', grad_fn=)

IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity 的用法在文档里有说，是这样的用的:
```
from transformers import AutoModelForSequenceClassification
from transformers import BertTokenizer
import torch

tokenizer=BertTokenizer.from_pretrained('IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity')
model=AutoModelForSequenceClassification.from_pretrained('IDEA-CCNL/Erlangshen-MegatronBert-1.3B-Similarity')

texta='今天的饭不好吃'
textb='今天心情不好'

output=model(torch.tensor([tokenizer.encode(texta,textb)]))
print(torch.nn.functional.softmax(output.logits,dim=-1))
```
