### ISSUE TITLE
使用Rangdeng-Pegasus系列，提示文件not found /cognitive_comp/dongxiaoqun/software/jieba/tmp/tmpk8ungvhc

### ISSUE THREAD

**Issue by jiangliqin** [IDEA-CCNL/Fengshenbang-LM#96]
使用Randeng-Pegasus-523M-Summary-Chinese
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/12250847/182058904-2df5e3c2-5083-47fe-9d94-146c03b08672.png">

请问可以提供这份自定义jieba分词文件吗？

**Comment by jiangliqin** [comment]
修改了jieba临时文件路径
但是结果并没有变化
<img width="646" alt="image" src="https://user-images.githubusercontent.com/12250847/182059515-1efe77a9-13bd-45db-b33f-124d3d5bf8b1.png">

**Comment by dongxqm** [comment]
hi， @jiangliqin  你好，你tokenizer的使用代码能否贴详细一点，方便我帮你定位问题。目前看你的截图，jieba分词已经导入成功了。

**Comment by jiangliqin** [comment]
你好，完全是示例代码
`from transformers import PegasusForConditionalGeneration
from tokenizers_pegasus import PegasusTokenizer

model = PegasusForConditionalGeneration.from_pretrained("IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese")
tokenizer = PegasusTokenizer.from_pretrained("IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese")

text = "据微信公众号“界面”报道，4日上午10点左右，中国发改委反垄断调查小组突击查访奔驰上海办事处，调取数据材料，并对多名奔驰高管进行了约谈。截止昨日晚9点，包括北京梅赛德斯-奔驰销售服务有限公司东区总经理在内的多名管理人员仍留在上海办公室内"
inputs = tokenizer(text, max_length=1024, return_tensors="pt")

summary_ids = model.generate(inputs["input_ids"])
tokenizer.batch_decode(summary_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

**Comment by dongxqm** [comment]
上面的“老鼠老鼠……”是模型的输出？还是输入？有什么其他报错吗？是切词不对吗？

**Comment by jiangliqin** [comment]
是输出，没有其他报错

**Comment by dongxqm** [comment]
<img width="1569" alt="图片" src="https://user-images.githubusercontent.com/107237598/182084040-e693e0a4-a747-4def-93ea-b2fb68d4023a.png">
我这边测试是没有问题的哈，建议再确认下model是否正常加载，tokenizer的切词是否正确，每一步都再打印出来看下

**Comment by jiangliqin** [comment]
Randeng-Pegasus-238M-Summary-Chinese模型就结果正常，Randeng-Pegasus-523M-Summary-Chinese还是结果不对

**Comment by dongxqm** [comment]
<img width="1914" alt="图片" src="https://user-images.githubusercontent.com/107237598/182276156-27d524e7-9aee-4eed-8852-e18bb3da0fe8.png">
清理一下hugging face的缓存试试，或者清理？

**Comment by oblialbum** [comment]
![image](https://user-images.githubusercontent.com/23495180/182438183-7371ef26-53cd-44fb-8651-642cce03840e.png)
我是在windows上将tokenizers_pegasus.py中的tmp.dir替换程一个本地文件夹，运行之后会自动下载。

**Comment by dongxqm** [comment]
@jiangliqin 问题解决了吗？

**Comment by jiangliqin** [comment]
> 

还是没有哦
