### ISSUE TITLE
The recall of coco-cn test data is not the same

### ISSUE THREAD

**Issue by ZJUzxf** [IDEA-CCNL/Fengshenbang-LM#99]
I have download the checkpoint Taiyi-CLIP-Roberta-102M-Chinese, but the recall of coco-cn test data is not the same as described, can you offer the evaluation code. Thanks

**Comment by Weifeng-Chen** [comment]
I've check it and update the result.(only a small error).  what's result did you get? As for the evaluation code, We will release it later.

**Comment by ZJUzxf** [comment]
I use the checkpoint and code in [Taiyi-CLIP-Roberta-102M-Chinese](https://huggingface.co/IDEA-CCNL/Taiyi-CLIP-Roberta-102M-Chinese), and get the recall results is 0.353,0.638,0.764, according to the https://github.com/ksOAn6g5/TaiSu/blob/6ba05de6474c893bc7391f5eb42a89d513b970a4/eval/ITRetrieval.py#L174, and the [Taiyi-CLIP-Roberta-large-326M-Chinese](https://huggingface.co/IDEA-CCNL/Taiyi-CLIP-Roberta-large-326M-Chinese) is right in the same way, i do not know why

**Comment by Weifeng-Chen** [comment]
For now, you can refer to https://github.com/Weifeng-Chen/DL_tools/blob/main/zeroshot_retrieval_evaluation.ipynb , which is not merged to this codebase for now. 
This is my evaluation script. You can check the algorithm and how the dataset loaded.
If you find some bugs in my script, plz inform me, thanks.

**Comment by ZJUzxf** [comment]
Thank you for your evaluation script, the result for coco-cn dataset is right now
